package com.xinov.academix.core.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxAdmissionDocuments generated by hbm2java
 */
@Entity
@Table(name = "acx_admission_documents")
public class AdmissionDocuments implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8730906018505871141L;
	
	private int id;
	private AdmissionInfo acxAdmissionInfo;
	private DocumentMaster acxDocumentMaster;

	public AdmissionDocuments() {
	}

	public AdmissionDocuments(int id, AdmissionInfo acxAdmissionInfo,
			DocumentMaster acxDocumentMaster) {
		this.id = id;
		this.acxAdmissionInfo = acxAdmissionInfo;
		this.acxDocumentMaster = acxDocumentMaster;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACX_ADMISSION_INFO_application_id", nullable = false)
	public AdmissionInfo getAcxAdmissionInfo() {
		return this.acxAdmissionInfo;
	}

	public void setAcxAdmissionInfo(AdmissionInfo acxAdmissionInfo) {
		this.acxAdmissionInfo = acxAdmissionInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACX_DOCUMENT_MASTER_id", nullable = false)
	public DocumentMaster getAcxDocumentMaster() {
		return this.acxDocumentMaster;
	}

	public void setAcxDocumentMaster(DocumentMaster acxDocumentMaster) {
		this.acxDocumentMaster = acxDocumentMaster;
	}

}
