package com.xinov.academix.core.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DocumentMaster generated by hbm2java
 */
@Entity
@Table(name = "acx_document_master")
public class DocumentMaster implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5158479167760839817L;
	
	private int id;
	private User usersByModifiedBy;
	private User usersByCreatedBy;
	private String documentName;
	private String documentPath;
	private Date createdDate;
	private Date modifiedDate;
	private Set<UserDocument> userDocuments = new HashSet<UserDocument>(
			0);
	private Set<AdmissionDocument> admissionDocuments = new HashSet<AdmissionDocument>(
			0);

	public DocumentMaster() {
	}

	public DocumentMaster(int id, User usersByCreatedBy,
			String documentName, String documentPath) {
		this.id = id;
		this.usersByCreatedBy = usersByCreatedBy;
		this.documentName = documentName;
		this.documentPath = documentPath;
	}

	public DocumentMaster(int id, User usersByModifiedBy,
			User UsersByCreatedBy, String documentName,
			String documentPath, Date createdDate, Date modifiedDate,
			Set<UserDocument> userDocuments,
			Set<AdmissionDocument> admissionDocuments) {
		this.id = id;
		this.usersByModifiedBy = usersByModifiedBy;
		this.usersByCreatedBy = UsersByCreatedBy;
		this.documentName = documentName;
		this.documentPath = documentPath;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.userDocuments = userDocuments;
		this.admissionDocuments = admissionDocuments;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modified_by")
	public User getUsersByModifiedBy() {
		return this.usersByModifiedBy;
	}

	public void setUsersByModifiedBy(User usersByModifiedBy) {
		this.usersByModifiedBy = usersByModifiedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public User getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(User usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@Column(name = "document_name", nullable = false)
	public String getDocumentName() {
		return this.documentName;
	}

	public void setDocumentName(String documentName) {
		this.documentName = documentName;
	}

	@Column(name = "document_path", nullable = false)
	public String getDocumentPath() {
		return this.documentPath;
	}

	public void setDocumentPath(String documentPath) {
		this.documentPath = documentPath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "DocumentMaster")
	public Set<UserDocument> getUserDocuments() {
		return this.userDocuments;
	}

	public void setUserDocuments(Set<UserDocument> userDocuments) {
		this.userDocuments = userDocuments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "DocumentMaster")
	public Set<AdmissionDocument> getAdmissionDocuments() {
		return this.admissionDocuments;
	}

	public void setAdmissionDocuments(
			Set<AdmissionDocument> admissionDocuments) {
		this.admissionDocuments = admissionDocuments;
	}

}
