package com.xinov.academix.core.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AcxExams generated by hbm2java
 */
@Entity
@Table(name = "acx_exams")
public class Examination implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7444828824900545034L;
	
	private int id;
	private SchoolInfo acxSchoolMaster;
	private String examName;
	private Date examStartDate;
	private Date examEndDate;
	private Set<ExamResult> acxExamResults = new HashSet<ExamResult>(0);
	private Set<ExamSeatingArrangement> acxExamSeatingArrangements = new HashSet<ExamSeatingArrangement>(
			0);
	private Set<ExamSchedule> acxExamSchedules = new HashSet<ExamSchedule>(
			0);

	public Examination() {
	}

	public Examination(int id, SchoolInfo acxSchoolMaster, String examName) {
		this.id = id;
		this.acxSchoolMaster = acxSchoolMaster;
		this.examName = examName;
	}

	public Examination(int id, SchoolInfo acxSchoolMaster, String examName,
			Date examStartDate, Date examEndDate,
			Set<ExamResult> acxExamResults,
			Set<ExamSeatingArrangement> acxExamSeatingArrangements,
			Set<ExamSchedule> acxExamSchedules) {
		this.id = id;
		this.acxSchoolMaster = acxSchoolMaster;
		this.examName = examName;
		this.examStartDate = examStartDate;
		this.examEndDate = examEndDate;
		this.acxExamResults = acxExamResults;
		this.acxExamSeatingArrangements = acxExamSeatingArrangements;
		this.acxExamSchedules = acxExamSchedules;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id", nullable = false)
	public SchoolInfo getAcxSchoolMaster() {
		return this.acxSchoolMaster;
	}

	public void setAcxSchoolMaster(SchoolInfo acxSchoolMaster) {
		this.acxSchoolMaster = acxSchoolMaster;
	}

	@Column(name = "exam_name", nullable = false, length = 45)
	public String getExamName() {
		return this.examName;
	}

	public void setExamName(String examName) {
		this.examName = examName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "exam_start_date", length = 19)
	public Date getExamStartDate() {
		return this.examStartDate;
	}

	public void setExamStartDate(Date examStartDate) {
		this.examStartDate = examStartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "exam_end_date", length = 19)
	public Date getExamEndDate() {
		return this.examEndDate;
	}

	public void setExamEndDate(Date examEndDate) {
		this.examEndDate = examEndDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxExams")
	public Set<ExamResult> getAcxExamResults() {
		return this.acxExamResults;
	}

	public void setAcxExamResults(Set<ExamResult> acxExamResults) {
		this.acxExamResults = acxExamResults;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxExams")
	public Set<ExamSeatingArrangement> getAcxExamSeatingArrangements() {
		return this.acxExamSeatingArrangements;
	}

	public void setAcxExamSeatingArrangements(
			Set<ExamSeatingArrangement> acxExamSeatingArrangements) {
		this.acxExamSeatingArrangements = acxExamSeatingArrangements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxExams")
	public Set<ExamSchedule> getAcxExamSchedules() {
		return this.acxExamSchedules;
	}

	public void setAcxExamSchedules(Set<ExamSchedule> acxExamSchedules) {
		this.acxExamSchedules = acxExamSchedules;
	}

}
