package com.xinov.academix.core.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxExamSeatingArrangement generated by hbm2java
 */
@Entity
@Table(name = "acx_exam_seating_arrangement")
public class ExamSeatingArrangement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 493843648948914534L;
	
	private int id;
	private Examination acxExams;
	private User acxUsers;
	private String hallNo;

	public ExamSeatingArrangement() {
	}

	public ExamSeatingArrangement(int id, Examination acxExams,
			User acxUsers, String hallNo) {
		this.id = id;
		this.acxExams = acxExams;
		this.acxUsers = acxUsers;
		this.hallNo = hallNo;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "exam_id", nullable = false)
	public Examination getAcxExams() {
		return this.acxExams;
	}

	public void setAcxExams(Examination acxExams) {
		this.acxExams = acxExams;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id", nullable = false)
	public User getAcxUsers() {
		return this.acxUsers;
	}

	public void setAcxUsers(User acxUsers) {
		this.acxUsers = acxUsers;
	}

	@Column(name = "hall_no", nullable = false, length = 45)
	public String getHallNo() {
		return this.hallNo;
	}

	public void setHallNo(String hallNo) {
		this.hallNo = hallNo;
	}

}
