package com.xinov.academix.core.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxExamResult generated by hbm2java
 */
@Entity
@Table(name = "acx_exam_result")
public class ExamResult implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8164093511560425335L;
	
	private int id;
	private Examination acxExams;
	private Subject acxSubjectMaster;
	private User acxUsersByStudentId;
	private User acxUsersByExaminorId;
	private Integer totalMarks;
	private Integer marksObtained;
	private String gradeObtained;
	private BigDecimal percentage;
	private String result;
	private String remarks;

	public ExamResult() {
	}

	public ExamResult(int id, Examination acxExams,
			Subject acxSubjectMaster, User acxUsersByStudentId,
			User acxUsersByExaminorId) {
		this.id = id;
		this.acxExams = acxExams;
		this.acxSubjectMaster = acxSubjectMaster;
		this.acxUsersByStudentId = acxUsersByStudentId;
		this.acxUsersByExaminorId = acxUsersByExaminorId;
	}

	public ExamResult(int id, Examination acxExams,
			Subject acxSubjectMaster, User acxUsersByStudentId,
			User acxUsersByExaminorId, Integer totalMarks,
			Integer marksObtained, String gradeObtained, BigDecimal percentage,
			String result, String remarks) {
		this.id = id;
		this.acxExams = acxExams;
		this.acxSubjectMaster = acxSubjectMaster;
		this.acxUsersByStudentId = acxUsersByStudentId;
		this.acxUsersByExaminorId = acxUsersByExaminorId;
		this.totalMarks = totalMarks;
		this.marksObtained = marksObtained;
		this.gradeObtained = gradeObtained;
		this.percentage = percentage;
		this.result = result;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "exam_id", nullable = false)
	public Examination getAcxExams() {
		return this.acxExams;
	}

	public void setAcxExams(Examination acxExams) {
		this.acxExams = acxExams;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_id", nullable = false)
	public Subject getAcxSubjectMaster() {
		return this.acxSubjectMaster;
	}

	public void setAcxSubjectMaster(Subject acxSubjectMaster) {
		this.acxSubjectMaster = acxSubjectMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id", nullable = false)
	public User getAcxUsersByStudentId() {
		return this.acxUsersByStudentId;
	}

	public void setAcxUsersByStudentId(User acxUsersByStudentId) {
		this.acxUsersByStudentId = acxUsersByStudentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "examinor_id", nullable = false)
	public User getAcxUsersByExaminorId() {
		return this.acxUsersByExaminorId;
	}

	public void setAcxUsersByExaminorId(User acxUsersByExaminorId) {
		this.acxUsersByExaminorId = acxUsersByExaminorId;
	}

	@Column(name = "total_marks")
	public Integer getTotalMarks() {
		return this.totalMarks;
	}

	public void setTotalMarks(Integer totalMarks) {
		this.totalMarks = totalMarks;
	}

	@Column(name = "marks_obtained")
	public Integer getMarksObtained() {
		return this.marksObtained;
	}

	public void setMarksObtained(Integer marksObtained) {
		this.marksObtained = marksObtained;
	}

	@Column(name = "grade_obtained", length = 45)
	public String getGradeObtained() {
		return this.gradeObtained;
	}

	public void setGradeObtained(String gradeObtained) {
		this.gradeObtained = gradeObtained;
	}

	@Column(name = "percentage", precision = 2)
	public BigDecimal getPercentage() {
		return this.percentage;
	}

	public void setPercentage(BigDecimal percentage) {
		this.percentage = percentage;
	}

	@Column(name = "result", length = 45)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Column(name = "remarks", length = 100)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
