package com.xinov.academix.core.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AcxExamSchedule generated by hbm2java
 */
@Entity
@Table(name = "acx_exam_schedule")
public class ExamSchedule implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1742117427680438701L;
	
	private int id;
	private ClassMaster acxClassMaster;
	private Examination acxExams;
	private Subject acxSubjectMaster;
	private User acxUsers;
	private Date date;
	private Date startTime;
	private Date endTime;

	public ExamSchedule() {
	}

	public ExamSchedule(int id, ClassMaster acxClassMaster,
			Examination acxExams, Subject acxSubjectMaster,
			User acxUsers, Date date) {
		this.id = id;
		this.acxClassMaster = acxClassMaster;
		this.acxExams = acxExams;
		this.acxSubjectMaster = acxSubjectMaster;
		this.acxUsers = acxUsers;
		this.date = date;
	}

	public ExamSchedule(int id, ClassMaster acxClassMaster,
			Examination acxExams, Subject acxSubjectMaster,
			User acxUsers, Date date, Date startTime, Date endTime) {
		this.id = id;
		this.acxClassMaster = acxClassMaster;
		this.acxExams = acxExams;
		this.acxSubjectMaster = acxSubjectMaster;
		this.acxUsers = acxUsers;
		this.date = date;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id", nullable = false)
	public ClassMaster getAcxClassMaster() {
		return this.acxClassMaster;
	}

	public void setAcxClassMaster(ClassMaster acxClassMaster) {
		this.acxClassMaster = acxClassMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "exam_id", nullable = false)
	public Examination getAcxExams() {
		return this.acxExams;
	}

	public void setAcxExams(Examination acxExams) {
		this.acxExams = acxExams;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_id", nullable = false)
	public Subject getAcxSubjectMaster() {
		return this.acxSubjectMaster;
	}

	public void setAcxSubjectMaster(Subject acxSubjectMaster) {
		this.acxSubjectMaster = acxSubjectMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "examinor_id", nullable = false)
	public User getAcxUsers() {
		return this.acxUsers;
	}

	public void setAcxUsers(User acxUsers) {
		this.acxUsers = acxUsers;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_time", length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

}
