package com.xinov.academix.core.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MeetingParticipents generated by hbm2java
 */
@Entity
@Table(name = "acx_meeting_participents")
public class MeetingParticipent implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1746651768914087494L;
	
	private int id;
	private Meeting meeting;
	private User user;

	public MeetingParticipent() {
	}

	public MeetingParticipent(int id, Meeting meeting,
			User Users) {
		this.id = id;
		this.meeting = meeting;
		this.user = Users;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "meeting_id", nullable = false)
	public Meeting getMeeting() {
		return this.meeting;
	}

	public void setMeeting(Meeting meeting) {
		this.meeting = meeting;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "participant_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
