package com.xinov.academix.core.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OnlinePoll generated by hbm2java
 */
@Entity
@Table(name = "acx_online_poll")
public class OnlinePoll implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5032312027439034331L;
	
	private int id;
	private SchoolInfo schoolInfo;
	private User user;
	private String topic;
	private Date startDate;
	private String endDate;
	private Set<PollVoter> pollVoters = new HashSet<PollVoter>(0);
	private Set<PollResult> pollResults = new HashSet<PollResult>(
			0);

	public OnlinePoll() {
	}

	public OnlinePoll(int id, SchoolInfo schoolInfo,
			User user, String topic, String endDate) {
		this.id = id;
		this.schoolInfo = schoolInfo;
		this.user = user;
		this.topic = topic;
		this.endDate = endDate;
	}

	public OnlinePoll(int id, SchoolInfo schoolInfo,
			User user, String topic, Date startDate, String endDate,
			Set<PollVoter> pollVoters,
			Set<PollResult> pollResults) {
		this.id = id;
		this.schoolInfo = schoolInfo;
		this.user = user;
		this.topic = topic;
		this.startDate = startDate;
		this.endDate = endDate;
		this.pollVoters = pollVoters;
		this.pollResults = pollResults;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id", nullable = false)
	public SchoolInfo getSchoolInfo() {
		return this.schoolInfo;
	}

	public void setSchoolInfo(SchoolInfo schoolInfo) {
		this.schoolInfo = schoolInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "issuer_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "topic", nullable = false)
	public String getTopic() {
		return this.topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "end_date", nullable = false, length = 45)
	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "OnlinePoll")
	public Set<PollVoter> getPollVoters() {
		return this.pollVoters;
	}

	public void setPollVoters(Set<PollVoter> pollVoters) {
		this.pollVoters = pollVoters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "OnlinePoll")
	public Set<PollResult> getPollResults() {
		return this.pollResults;
	}

	public void setPollResults(Set<PollResult> pollResults) {
		this.pollResults = pollResults;
	}

}
