package com.xinov.academix.core.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PollVoters generated by hbm2java
 */
@Entity
@Table(name = "acx_poll_voters")
public class PollVoter implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6265418090270033086L;
	
	private int id;
	private OnlinePoll onlinePoll;
	private User user;

	public PollVoter() {
	}

	public PollVoter(int id, OnlinePoll onlinePoll, User user) {
		this.id = id;
		this.onlinePoll = onlinePoll;
		this.user = user;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "poll_id", nullable = false)
	public OnlinePoll getOnlinePoll() {
		return this.onlinePoll;
	}

	public void setOnlinePoll(OnlinePoll onlinePoll) {
		this.onlinePoll = onlinePoll;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "voter_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
