package com.xinov.academix.core.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PollResults generated by hbm2java
 */
@Entity
@Table(name = "_poll_results")
public class PollResult implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7041902334107592865L;
	
	private int id;
	private OnlinePoll onlinePoll;
	private String answer;
	private int numberOfVotes;

	public PollResult() {
	}

	public PollResult(int id, OnlinePoll onlinePoll, String answer,
			int numberOfVotes) {
		this.id = id;
		this.onlinePoll = onlinePoll;
		this.answer = answer;
		this.numberOfVotes = numberOfVotes;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "poll_id", nullable = false)
	public OnlinePoll getOnlinePoll() {
		return this.onlinePoll;
	}

	public void setOnlinePoll(OnlinePoll onlinePoll) {
		this.onlinePoll = onlinePoll;
	}

	@Column(name = "answer", nullable = false, length = 45)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	@Column(name = "number_of_votes", nullable = false)
	public int getNumberOfVotes() {
		return this.numberOfVotes;
	}

	public void setNumberOfVotes(int numberOfVotes) {
		this.numberOfVotes = numberOfVotes;
	}

}
