package com.xinov.academix.core.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AcxSchoolMaster generated by hbm2java
 */
@Entity
@Table(name = "acx_school_master", uniqueConstraints = {
		@UniqueConstraint(columnNames = "phone_no"),
		@UniqueConstraint(columnNames = "email_id") })
public class SchoolInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1550389012008002471L;
	
	private int id;
	private String name;
	private String address;
	private String phoneNo;
	private String emailId;
	private Set<Notice> acxNoticeses = new HashSet<Notice>(0);
	private Set<OnlinePoll> acxOnlinePolls = new HashSet<OnlinePoll>(0);
	private Set<User> acxUserses = new HashSet<User>(0);
	private Set<Attendance> acxAttendances = new HashSet<Attendance>(0);
	private Set<Meetings> acxMeetingses = new HashSet<Meetings>(0);
	private Set<ClassMaster> acxClassMasters = new HashSet<ClassMaster>(0);
	private Set<Examination> acxExamses = new HashSet<Examination>(0);

	public SchoolInfo() {
	}

	public SchoolInfo(int id, String name, String address, String phoneNo,
			String emailId) {
		this.id = id;
		this.name = name;
		this.address = address;
		this.phoneNo = phoneNo;
		this.emailId = emailId;
	}

	public SchoolInfo(int id, String name, String address, String phoneNo,
			String emailId, Set<Notice> acxNoticeses,
			Set<OnlinePoll> acxOnlinePolls, Set<User> acxUserses,
			Set<Attendance> acxAttendances, Set<Meetings> acxMeetingses,
			Set<ClassMaster> acxClassMasters, Set<Examination> acxExamses) {
		this.id = id;
		this.name = name;
		this.address = address;
		this.phoneNo = phoneNo;
		this.emailId = emailId;
		this.acxNoticeses = acxNoticeses;
		this.acxOnlinePolls = acxOnlinePolls;
		this.acxUserses = acxUserses;
		this.acxAttendances = acxAttendances;
		this.acxMeetingses = acxMeetingses;
		this.acxClassMasters = acxClassMasters;
		this.acxExamses = acxExamses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone_no", unique = true, nullable = false, length = 45)
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Column(name = "email_id", unique = true, nullable = false, length = 45)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSchoolMaster")
	public Set<Notice> getAcxNoticeses() {
		return this.acxNoticeses;
	}

	public void setAcxNoticeses(Set<Notice> acxNoticeses) {
		this.acxNoticeses = acxNoticeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSchoolMaster")
	public Set<OnlinePoll> getAcxOnlinePolls() {
		return this.acxOnlinePolls;
	}

	public void setAcxOnlinePolls(Set<OnlinePoll> acxOnlinePolls) {
		this.acxOnlinePolls = acxOnlinePolls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSchoolMaster")
	public Set<User> getAcxUserses() {
		return this.acxUserses;
	}

	public void setAcxUserses(Set<User> acxUserses) {
		this.acxUserses = acxUserses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSchoolMaster")
	public Set<Attendance> getAcxAttendances() {
		return this.acxAttendances;
	}

	public void setAcxAttendances(Set<Attendance> acxAttendances) {
		this.acxAttendances = acxAttendances;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSchoolMaster")
	public Set<Meetings> getAcxMeetingses() {
		return this.acxMeetingses;
	}

	public void setAcxMeetingses(Set<Meetings> acxMeetingses) {
		this.acxMeetingses = acxMeetingses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSchoolMaster")
	public Set<ClassMaster> getAcxClassMasters() {
		return this.acxClassMasters;
	}

	public void setAcxClassMasters(Set<ClassMaster> acxClassMasters) {
		this.acxClassMasters = acxClassMasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSchoolMaster")
	public Set<Examination> getAcxExamses() {
		return this.acxExamses;
	}

	public void setAcxExamses(Set<Examination> acxExamses) {
		this.acxExamses = acxExamses;
	}

}
