package com.xinov.academix.core.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SchoolMaster generated by hbm2java
 */
@Entity
@Table(name = "acx_school_master", uniqueConstraints = {
		@UniqueConstraint(columnNames = "phone_no"),
		@UniqueConstraint(columnNames = "email_id") })
public class SchoolInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1550389012008002471L;
	
	private int id;
	private String name;
	private String address;
	private String phoneNo;
	private String emailId;
	private Set<Notice> notices = new HashSet<Notice>(0);
	private Set<OnlinePoll> onlinePolls = new HashSet<OnlinePoll>(0);
	private Set<User> users = new HashSet<User>(0);
	private Set<Attendance> attendances = new HashSet<Attendance>(0);
	private Set<Meeting> meetings = new HashSet<Meeting>(0);
	private Set<ClassMaster> classMasters = new HashSet<ClassMaster>(0);
	private Set<Examination> examinations = new HashSet<Examination>(0);

	public SchoolInfo() {
	}

	public SchoolInfo(int id, String name, String address, String phoneNo,
			String emailId) {
		this.id = id;
		this.name = name;
		this.address = address;
		this.phoneNo = phoneNo;
		this.emailId = emailId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone_no", unique = true, nullable = false, length = 45)
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Column(name = "email_id", unique = true, nullable = false, length = 45)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "SchoolMaster")
	public Set<Notice> getNotices() {
		return this.notices;
	}

	public void setNotices(Set<Notice> notices) {
		this.notices = notices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "SchoolMaster")
	public Set<OnlinePoll> getOnlinePolls() {
		return this.onlinePolls;
	}

	public void setOnlinePolls(Set<OnlinePoll> onlinePolls) {
		this.onlinePolls = onlinePolls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "SchoolMaster")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "SchoolMaster")
	public Set<Attendance> getAttendances() {
		return this.attendances;
	}

	public void setAttendances(Set<Attendance> attendances) {
		this.attendances = attendances;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "SchoolMaster")
	public Set<Meeting> getMeetings() {
		return this.meetings;
	}

	public void setMeetings(Set<Meeting> meetings) {
		this.meetings = meetings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "SchoolMaster")
	public Set<ClassMaster> getClassMasters() {
		return this.classMasters;
	}

	public void setClassMasters(Set<ClassMaster> classMasters) {
		this.classMasters = classMasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "SchoolMaster")
	public Set<Examination> getExaminations() {
		return this.examinations;
	}

	public void setExaminations(Set<Examination> examinations) {
		this.examinations = examinations;
	}

}
