package com.xinov.academix.core.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AcxStatusMaster generated by hbm2java
 */
@Entity
@Table(name = "acx_status_master", uniqueConstraints = @UniqueConstraint(columnNames = "title"))
public class Status implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2264546371396156117L;
	
	private int id;
	private String title;
	private String type;
	private Set<AdmissionFees> acxAdmissionFeeses = new HashSet<AdmissionFees>(
			0);
	private Set<Meetings> acxMeetingses = new HashSet<Meetings>(0);
	private Set<AdmissionInfo> acxAdmissionInfos = new HashSet<AdmissionInfo>(
			0);

	public Status() {
	}

	public Status(int id, String title, String type) {
		this.id = id;
		this.title = title;
		this.type = type;
	}

	public Status(int id, String title, String type,
			Set<AdmissionFees> acxAdmissionFeeses,
			Set<Meetings> acxMeetingses,
			Set<AdmissionInfo> acxAdmissionInfos) {
		this.id = id;
		this.title = title;
		this.type = type;
		this.acxAdmissionFeeses = acxAdmissionFeeses;
		this.acxMeetingses = acxMeetingses;
		this.acxAdmissionInfos = acxAdmissionInfos;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "title", unique = true, nullable = false, length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxStatusMaster")
	public Set<AdmissionFees> getAcxAdmissionFeeses() {
		return this.acxAdmissionFeeses;
	}

	public void setAcxAdmissionFeeses(Set<AdmissionFees> acxAdmissionFeeses) {
		this.acxAdmissionFeeses = acxAdmissionFeeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxStatusMaster")
	public Set<Meetings> getAcxMeetingses() {
		return this.acxMeetingses;
	}

	public void setAcxMeetingses(Set<Meetings> acxMeetingses) {
		this.acxMeetingses = acxMeetingses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxStatusMaster")
	public Set<AdmissionInfo> getAcxAdmissionInfos() {
		return this.acxAdmissionInfos;
	}

	public void setAcxAdmissionInfos(Set<AdmissionInfo> acxAdmissionInfos) {
		this.acxAdmissionInfos = acxAdmissionInfos;
	}

}
