package com.xinov.academix.core.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AcxSubjectMaster generated by hbm2java
 */
@Entity
@Table(name = "acx_subject_master", uniqueConstraints = @UniqueConstraint(columnNames = "title"))
public class Subject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2378002417524065981L;
	
	private int id;
	private String title;
	private Set<TeacherSubject> acxTeacherSubjectses = new HashSet<TeacherSubject>(
			0);
	private Set<ExamResult> acxExamResults = new HashSet<ExamResult>(0);
	private Set<ExamSchedule> acxExamSchedules = new HashSet<ExamSchedule>(
			0);
	private Set<Scheduler> acxSchedulers = new HashSet<Scheduler>(0);

	public Subject() {
	}

	public Subject(int id, String title) {
		this.id = id;
		this.title = title;
	}

	public Subject(int id, String title,
			Set<TeacherSubject> acxTeacherSubjectses,
			Set<ExamResult> acxExamResults,
			Set<ExamSchedule> acxExamSchedules,
			Set<Scheduler> acxSchedulers) {
		this.id = id;
		this.title = title;
		this.acxTeacherSubjectses = acxTeacherSubjectses;
		this.acxExamResults = acxExamResults;
		this.acxExamSchedules = acxExamSchedules;
		this.acxSchedulers = acxSchedulers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "title", unique = true, nullable = false, length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSubjectMaster")
	public Set<TeacherSubject> getAcxTeacherSubjectses() {
		return this.acxTeacherSubjectses;
	}

	public void setAcxTeacherSubjectses(
			Set<TeacherSubject> acxTeacherSubjectses) {
		this.acxTeacherSubjectses = acxTeacherSubjectses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSubjectMaster")
	public Set<ExamResult> getAcxExamResults() {
		return this.acxExamResults;
	}

	public void setAcxExamResults(Set<ExamResult> acxExamResults) {
		this.acxExamResults = acxExamResults;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSubjectMaster")
	public Set<ExamSchedule> getAcxExamSchedules() {
		return this.acxExamSchedules;
	}

	public void setAcxExamSchedules(Set<ExamSchedule> acxExamSchedules) {
		this.acxExamSchedules = acxExamSchedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSubjectMaster")
	public Set<Scheduler> getAcxSchedulers() {
		return this.acxSchedulers;
	}

	public void setAcxSchedulers(Set<Scheduler> acxSchedulers) {
		this.acxSchedulers = acxSchedulers;
	}

}
