package com.xinov.academix.core.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SubjectMaster generated by hbm2java
 */
@Entity
@Table(name = "acx_subject_master", uniqueConstraints = @UniqueConstraint(columnNames = "title"))
public class Subject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2378002417524065981L;
	
	private int id;
	private String title;
	private Set<TeacherSubject> teacherSubjects = new HashSet<TeacherSubject>(
			0);
	private Set<ExamResult> examResults = new HashSet<ExamResult>(0);
	private Set<ExamSchedule> examSchedules = new HashSet<ExamSchedule>(
			0);
	private Set<Scheduler> schedulers = new HashSet<Scheduler>(0);

	public Subject() {
	}

	public Subject(int id, String title) {
		this.id = id;
		this.title = title;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "title", unique = true, nullable = false, length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "SubjectMaster")
	public Set<TeacherSubject> getTeacherSubjects() {
		return this.teacherSubjects;
	}

	public void setTeacherSubjects(
			Set<TeacherSubject> teacherSubjects) {
		this.teacherSubjects = teacherSubjects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "SubjectMaster")
	public Set<ExamResult> getExamResults() {
		return this.examResults;
	}

	public void setExamResults(Set<ExamResult> examResults) {
		this.examResults = examResults;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "SubjectMaster")
	public Set<ExamSchedule> getExamSchedules() {
		return this.examSchedules;
	}

	public void setExamSchedules(Set<ExamSchedule> examSchedules) {
		this.examSchedules = examSchedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "SubjectMaster")
	public Set<Scheduler> getSchedulers() {
		return this.schedulers;
	}

	public void setSchedulers(Set<Scheduler> schedulers) {
		this.schedulers = schedulers;
	}

}
