package com.xinov.academix.core.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TeacherInfo generated by hbm2java
 */
@Entity
@Table(name = "acx_teacher_info")
public class TeacherInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2038498675872269849L;
	
	private int id;
	private User user;
	private String qualification;

	public TeacherInfo() {
	}

	public TeacherInfo(int id, User user, String qualification) {
		this.id = id;
		this.user = user;
		this.qualification = qualification;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teacher_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "qualification", nullable = false, length = 45)
	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

}
