package com.xinov.academix.core.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxTeacherSubjects generated by hbm2java
 */
@Entity
@Table(name = "acx_teacher_subjects")
public class TeacherSubject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9040758994704881371L;
	
	private int id;
	private Subject acxSubjectMaster;
	private User acxUsers;

	public TeacherSubject() {
	}

	public TeacherSubject(int id, Subject acxSubjectMaster,
			User acxUsers) {
		this.id = id;
		this.acxSubjectMaster = acxSubjectMaster;
		this.acxUsers = acxUsers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_id", nullable = false)
	public Subject getAcxSubjectMaster() {
		return this.acxSubjectMaster;
	}

	public void setAcxSubjectMaster(Subject acxSubjectMaster) {
		this.acxSubjectMaster = acxSubjectMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teacher_id", nullable = false)
	public User getAcxUsers() {
		return this.acxUsers;
	}

	public void setAcxUsers(User acxUsers) {
		this.acxUsers = acxUsers;
	}

}
