package com.xinov.academix.core.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxUserRoles generated by hbm2java
 */
@Entity
@Table(name = "acx_user_roles")
public class UserRoles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1211033512536008801L;
	
	private int id;
	private Role acxRoleMaster;
	private User acxUsers;

	public UserRoles() {
	}

	public UserRoles(int id, Role acxRoleMaster, User acxUsers) {
		this.id = id;
		this.acxRoleMaster = acxRoleMaster;
		this.acxUsers = acxUsers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false)
	public Role getAcxRoleMaster() {
		return this.acxRoleMaster;
	}

	public void setAcxRoleMaster(Role acxRoleMaster) {
		this.acxRoleMaster = acxRoleMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getAcxUsers() {
		return this.acxUsers;
	}

	public void setAcxUsers(User acxUsers) {
		this.acxUsers = acxUsers;
	}

}
