package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxAdmissionDocuments generated by hbm2java
 */
@Entity
@Table(name = "acx_admission_documents")
public class AcxAdmissionDocuments implements java.io.Serializable {

	private int id;
	private AcxAdmissionInfo acxAdmissionInfo;
	private AcxDocumentMaster acxDocumentMaster;

	public AcxAdmissionDocuments() {
	}

	public AcxAdmissionDocuments(int id, AcxAdmissionInfo acxAdmissionInfo,
			AcxDocumentMaster acxDocumentMaster) {
		this.id = id;
		this.acxAdmissionInfo = acxAdmissionInfo;
		this.acxDocumentMaster = acxDocumentMaster;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACX_ADMISSION_INFO_application_id", nullable = false)
	public AcxAdmissionInfo getAcxAdmissionInfo() {
		return this.acxAdmissionInfo;
	}

	public void setAcxAdmissionInfo(AcxAdmissionInfo acxAdmissionInfo) {
		this.acxAdmissionInfo = acxAdmissionInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACX_DOCUMENT_MASTER_id", nullable = false)
	public AcxDocumentMaster getAcxDocumentMaster() {
		return this.acxDocumentMaster;
	}

	public void setAcxDocumentMaster(AcxDocumentMaster acxDocumentMaster) {
		this.acxDocumentMaster = acxDocumentMaster;
	}

}
