package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AcxAttendance generated by hbm2java
 */
public class AcxAttendance implements java.io.Serializable {

	private int id;
	private int schoolId;
	private Date date;
	private int classId;
	private String teacherId;
	private String studentId;
	private boolean present;
	private String absentReason;

	public AcxAttendance() {
	}

	public AcxAttendance(int id, int schoolId, int classId, String teacherId,
			String studentId, boolean present) {
		this.id = id;
		this.schoolId = schoolId;
		this.classId = classId;
		this.teacherId = teacherId;
		this.studentId = studentId;
		this.present = present;
	}

	public AcxAttendance(int id, int schoolId, Date date, int classId,
			String teacherId, String studentId, boolean present,
			String absentReason) {
		this.id = id;
		this.schoolId = schoolId;
		this.date = date;
		this.classId = classId;
		this.teacherId = teacherId;
		this.studentId = studentId;
		this.present = present;
		this.absentReason = absentReason;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(int schoolId) {
		this.schoolId = schoolId;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public int getClassId() {
		return this.classId;
	}

	public void setClassId(int classId) {
		this.classId = classId;
	}

	public String getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(String teacherId) {
		this.teacherId = teacherId;
	}

	public String getStudentId() {
		return this.studentId;
	}

	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	public boolean isPresent() {
		return this.present;
	}

	public void setPresent(boolean present) {
		this.present = present;
	}

	public String getAbsentReason() {
		return this.absentReason;
	}

	public void setAbsentReason(String absentReason) {
		this.absentReason = absentReason;
	}

}
