package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

/**
 * AcxAdmissionFees generated by hbm2java
 */
public class AcxAdmissionFees implements java.io.Serializable {

	private int id;
	private String applicationId;
	private int feesId;
	private int feesStatusId;

	public AcxAdmissionFees() {
	}

	public AcxAdmissionFees(int id, String applicationId, int feesId,
			int feesStatusId) {
		this.id = id;
		this.applicationId = applicationId;
		this.feesId = feesId;
		this.feesStatusId = feesStatusId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(String applicationId) {
		this.applicationId = applicationId;
	}

	public int getFeesId() {
		return this.feesId;
	}

	public void setFeesId(int feesId) {
		this.feesId = feesId;
	}

	public int getFeesStatusId() {
		return this.feesStatusId;
	}

	public void setFeesStatusId(int feesStatusId) {
		this.feesStatusId = feesStatusId;
	}

}
