package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AcxAttendance generated by hbm2java
 */
@Entity
@Table(name = "acx_attendance")
public class AcxAttendance implements java.io.Serializable {

	private int id;
	private AcxClassMaster acxClassMaster;
	private AcxSchoolMaster acxSchoolMaster;
	private AcxUsers acxUsersByTeacherId;
	private AcxUsers acxUsersByStudentId;
	private Date date;
	private boolean present;
	private String absentReason;

	public AcxAttendance() {
	}

	public AcxAttendance(int id, AcxClassMaster acxClassMaster,
			AcxSchoolMaster acxSchoolMaster, AcxUsers acxUsersByTeacherId,
			AcxUsers acxUsersByStudentId, boolean present) {
		this.id = id;
		this.acxClassMaster = acxClassMaster;
		this.acxSchoolMaster = acxSchoolMaster;
		this.acxUsersByTeacherId = acxUsersByTeacherId;
		this.acxUsersByStudentId = acxUsersByStudentId;
		this.present = present;
	}

	public AcxAttendance(int id, AcxClassMaster acxClassMaster,
			AcxSchoolMaster acxSchoolMaster, AcxUsers acxUsersByTeacherId,
			AcxUsers acxUsersByStudentId, Date date, boolean present,
			String absentReason) {
		this.id = id;
		this.acxClassMaster = acxClassMaster;
		this.acxSchoolMaster = acxSchoolMaster;
		this.acxUsersByTeacherId = acxUsersByTeacherId;
		this.acxUsersByStudentId = acxUsersByStudentId;
		this.date = date;
		this.present = present;
		this.absentReason = absentReason;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id", nullable = false)
	public AcxClassMaster getAcxClassMaster() {
		return this.acxClassMaster;
	}

	public void setAcxClassMaster(AcxClassMaster acxClassMaster) {
		this.acxClassMaster = acxClassMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id", nullable = false)
	public AcxSchoolMaster getAcxSchoolMaster() {
		return this.acxSchoolMaster;
	}

	public void setAcxSchoolMaster(AcxSchoolMaster acxSchoolMaster) {
		this.acxSchoolMaster = acxSchoolMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teacher_id", nullable = false)
	public AcxUsers getAcxUsersByTeacherId() {
		return this.acxUsersByTeacherId;
	}

	public void setAcxUsersByTeacherId(AcxUsers acxUsersByTeacherId) {
		this.acxUsersByTeacherId = acxUsersByTeacherId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id", nullable = false)
	public AcxUsers getAcxUsersByStudentId() {
		return this.acxUsersByStudentId;
	}

	public void setAcxUsersByStudentId(AcxUsers acxUsersByStudentId) {
		this.acxUsersByStudentId = acxUsersByStudentId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "present", nullable = false)
	public boolean isPresent() {
		return this.present;
	}

	public void setPresent(boolean present) {
		this.present = present;
	}

	@Column(name = "absent_reason", length = 100)
	public String getAbsentReason() {
		return this.absentReason;
	}

	public void setAbsentReason(String absentReason) {
		this.absentReason = absentReason;
	}

}
