package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxAdmissionFees generated by hbm2java
 */
@Entity
@Table(name = "acx_admission_fees")
public class AcxAdmissionFees implements java.io.Serializable {

	private int id;
	private AcxAdmissionInfo acxAdmissionInfo;
	private AcxFeesMaster acxFeesMaster;
	private AcxStatusMaster acxStatusMaster;

	public AcxAdmissionFees() {
	}

	public AcxAdmissionFees(int id, AcxAdmissionInfo acxAdmissionInfo,
			AcxFeesMaster acxFeesMaster, AcxStatusMaster acxStatusMaster) {
		this.id = id;
		this.acxAdmissionInfo = acxAdmissionInfo;
		this.acxFeesMaster = acxFeesMaster;
		this.acxStatusMaster = acxStatusMaster;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "application_id", nullable = false)
	public AcxAdmissionInfo getAcxAdmissionInfo() {
		return this.acxAdmissionInfo;
	}

	public void setAcxAdmissionInfo(AcxAdmissionInfo acxAdmissionInfo) {
		this.acxAdmissionInfo = acxAdmissionInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fees_id", nullable = false)
	public AcxFeesMaster getAcxFeesMaster() {
		return this.acxFeesMaster;
	}

	public void setAcxFeesMaster(AcxFeesMaster acxFeesMaster) {
		this.acxFeesMaster = acxFeesMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fees_status_id", nullable = false)
	public AcxStatusMaster getAcxStatusMaster() {
		return this.acxStatusMaster;
	}

	public void setAcxStatusMaster(AcxStatusMaster acxStatusMaster) {
		this.acxStatusMaster = acxStatusMaster;
	}

}
