package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AcxAdmissionInfo generated by hbm2java
 */
public class AcxAdmissionInfo implements java.io.Serializable {

	private String applicationId;
	private String applicantName;
	private String applicantContactNo;
	private String applicantEmail;
	private int applicationStatus;
	private String appkicationStatusModifiedBy;
	private Date appkicationStatusModifiedOn;
	private String remarks;

	public AcxAdmissionInfo() {
	}

	public AcxAdmissionInfo(String applicationId, String applicantName,
			String applicantContactNo, String applicantEmail,
			int applicationStatus, String appkicationStatusModifiedBy) {
		this.applicationId = applicationId;
		this.applicantName = applicantName;
		this.applicantContactNo = applicantContactNo;
		this.applicantEmail = applicantEmail;
		this.applicationStatus = applicationStatus;
		this.appkicationStatusModifiedBy = appkicationStatusModifiedBy;
	}

	public AcxAdmissionInfo(String applicationId, String applicantName,
			String applicantContactNo, String applicantEmail,
			int applicationStatus, String appkicationStatusModifiedBy,
			Date appkicationStatusModifiedOn, String remarks) {
		this.applicationId = applicationId;
		this.applicantName = applicantName;
		this.applicantContactNo = applicantContactNo;
		this.applicantEmail = applicantEmail;
		this.applicationStatus = applicationStatus;
		this.appkicationStatusModifiedBy = appkicationStatusModifiedBy;
		this.appkicationStatusModifiedOn = appkicationStatusModifiedOn;
		this.remarks = remarks;
	}

	public String getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(String applicationId) {
		this.applicationId = applicationId;
	}

	public String getApplicantName() {
		return this.applicantName;
	}

	public void setApplicantName(String applicantName) {
		this.applicantName = applicantName;
	}

	public String getApplicantContactNo() {
		return this.applicantContactNo;
	}

	public void setApplicantContactNo(String applicantContactNo) {
		this.applicantContactNo = applicantContactNo;
	}

	public String getApplicantEmail() {
		return this.applicantEmail;
	}

	public void setApplicantEmail(String applicantEmail) {
		this.applicantEmail = applicantEmail;
	}

	public int getApplicationStatus() {
		return this.applicationStatus;
	}

	public void setApplicationStatus(int applicationStatus) {
		this.applicationStatus = applicationStatus;
	}

	public String getAppkicationStatusModifiedBy() {
		return this.appkicationStatusModifiedBy;
	}

	public void setAppkicationStatusModifiedBy(
			String appkicationStatusModifiedBy) {
		this.appkicationStatusModifiedBy = appkicationStatusModifiedBy;
	}

	public Date getAppkicationStatusModifiedOn() {
		return this.appkicationStatusModifiedOn;
	}

	public void setAppkicationStatusModifiedOn(Date appkicationStatusModifiedOn) {
		this.appkicationStatusModifiedOn = appkicationStatusModifiedOn;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
