package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

/**
 * AcxClassMaster generated by hbm2java
 */
public class AcxClassMaster implements java.io.Serializable {

	private int id;
	private String title;
	private int schoolId;

	public AcxClassMaster() {
	}

	public AcxClassMaster(int id, String title, int schoolId) {
		this.id = id;
		this.title = title;
		this.schoolId = schoolId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public int getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(int schoolId) {
		this.schoolId = schoolId;
	}

}
