package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AcxClassMaster generated by hbm2java
 */
@Entity
@Table(name = "acx_class_master")
public class AcxClassMaster implements java.io.Serializable {

	private int id;
	private AcxSchoolMaster acxSchoolMaster;
	private String title;
	private Set<AcxAttendance> acxAttendances = new HashSet<AcxAttendance>(0);
	private Set<AcxNotices> acxNoticeses = new HashSet<AcxNotices>(0);
	private Set<AcxExamSchedule> acxExamSchedules = new HashSet<AcxExamSchedule>(
			0);
	private Set<AcxStudentInfo> acxStudentInfos = new HashSet<AcxStudentInfo>(0);
	private Set<AcxScheduler> acxSchedulers = new HashSet<AcxScheduler>(0);

	public AcxClassMaster() {
	}

	public AcxClassMaster(int id, AcxSchoolMaster acxSchoolMaster, String title) {
		this.id = id;
		this.acxSchoolMaster = acxSchoolMaster;
		this.title = title;
	}

	public AcxClassMaster(int id, AcxSchoolMaster acxSchoolMaster,
			String title, Set<AcxAttendance> acxAttendances,
			Set<AcxNotices> acxNoticeses,
			Set<AcxExamSchedule> acxExamSchedules,
			Set<AcxStudentInfo> acxStudentInfos, Set<AcxScheduler> acxSchedulers) {
		this.id = id;
		this.acxSchoolMaster = acxSchoolMaster;
		this.title = title;
		this.acxAttendances = acxAttendances;
		this.acxNoticeses = acxNoticeses;
		this.acxExamSchedules = acxExamSchedules;
		this.acxStudentInfos = acxStudentInfos;
		this.acxSchedulers = acxSchedulers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id", nullable = false)
	public AcxSchoolMaster getAcxSchoolMaster() {
		return this.acxSchoolMaster;
	}

	public void setAcxSchoolMaster(AcxSchoolMaster acxSchoolMaster) {
		this.acxSchoolMaster = acxSchoolMaster;
	}

	@Column(name = "title", nullable = false, length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxClassMaster")
	public Set<AcxAttendance> getAcxAttendances() {
		return this.acxAttendances;
	}

	public void setAcxAttendances(Set<AcxAttendance> acxAttendances) {
		this.acxAttendances = acxAttendances;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxClassMaster")
	public Set<AcxNotices> getAcxNoticeses() {
		return this.acxNoticeses;
	}

	public void setAcxNoticeses(Set<AcxNotices> acxNoticeses) {
		this.acxNoticeses = acxNoticeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxClassMaster")
	public Set<AcxExamSchedule> getAcxExamSchedules() {
		return this.acxExamSchedules;
	}

	public void setAcxExamSchedules(Set<AcxExamSchedule> acxExamSchedules) {
		this.acxExamSchedules = acxExamSchedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxClassMaster")
	public Set<AcxStudentInfo> getAcxStudentInfos() {
		return this.acxStudentInfos;
	}

	public void setAcxStudentInfos(Set<AcxStudentInfo> acxStudentInfos) {
		this.acxStudentInfos = acxStudentInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxClassMaster")
	public Set<AcxScheduler> getAcxSchedulers() {
		return this.acxSchedulers;
	}

	public void setAcxSchedulers(Set<AcxScheduler> acxSchedulers) {
		this.acxSchedulers = acxSchedulers;
	}

}
