package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AcxDocumentMaster generated by hbm2java
 */
@Entity
@Table(name = "acx_document_master")
public class AcxDocumentMaster implements java.io.Serializable {

	private int id;
	private AcxUsers acxUsersByModifiedBy;
	private AcxUsers acxUsersByCreatedBy;
	private String documentName;
	private String documentPath;
	private Date createdDate;
	private Date modifiedDate;
	private Set<AcxUserDocuments> acxUserDocumentses = new HashSet<AcxUserDocuments>(
			0);
	private Set<AcxAdmissionDocuments> acxAdmissionDocumentses = new HashSet<AcxAdmissionDocuments>(
			0);

	public AcxDocumentMaster() {
	}

	public AcxDocumentMaster(int id, AcxUsers acxUsersByCreatedBy,
			String documentName, String documentPath) {
		this.id = id;
		this.acxUsersByCreatedBy = acxUsersByCreatedBy;
		this.documentName = documentName;
		this.documentPath = documentPath;
	}

	public AcxDocumentMaster(int id, AcxUsers acxUsersByModifiedBy,
			AcxUsers acxUsersByCreatedBy, String documentName,
			String documentPath, Date createdDate, Date modifiedDate,
			Set<AcxUserDocuments> acxUserDocumentses,
			Set<AcxAdmissionDocuments> acxAdmissionDocumentses) {
		this.id = id;
		this.acxUsersByModifiedBy = acxUsersByModifiedBy;
		this.acxUsersByCreatedBy = acxUsersByCreatedBy;
		this.documentName = documentName;
		this.documentPath = documentPath;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.acxUserDocumentses = acxUserDocumentses;
		this.acxAdmissionDocumentses = acxAdmissionDocumentses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modified_by")
	public AcxUsers getAcxUsersByModifiedBy() {
		return this.acxUsersByModifiedBy;
	}

	public void setAcxUsersByModifiedBy(AcxUsers acxUsersByModifiedBy) {
		this.acxUsersByModifiedBy = acxUsersByModifiedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public AcxUsers getAcxUsersByCreatedBy() {
		return this.acxUsersByCreatedBy;
	}

	public void setAcxUsersByCreatedBy(AcxUsers acxUsersByCreatedBy) {
		this.acxUsersByCreatedBy = acxUsersByCreatedBy;
	}

	@Column(name = "document_name", nullable = false)
	public String getDocumentName() {
		return this.documentName;
	}

	public void setDocumentName(String documentName) {
		this.documentName = documentName;
	}

	@Column(name = "document_path", nullable = false)
	public String getDocumentPath() {
		return this.documentPath;
	}

	public void setDocumentPath(String documentPath) {
		this.documentPath = documentPath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxDocumentMaster")
	public Set<AcxUserDocuments> getAcxUserDocumentses() {
		return this.acxUserDocumentses;
	}

	public void setAcxUserDocumentses(Set<AcxUserDocuments> acxUserDocumentses) {
		this.acxUserDocumentses = acxUserDocumentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxDocumentMaster")
	public Set<AcxAdmissionDocuments> getAcxAdmissionDocumentses() {
		return this.acxAdmissionDocumentses;
	}

	public void setAcxAdmissionDocumentses(
			Set<AcxAdmissionDocuments> acxAdmissionDocumentses) {
		this.acxAdmissionDocumentses = acxAdmissionDocumentses;
	}

}
