package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AcxDocumentMaster generated by hbm2java
 */
public class AcxDocumentMaster implements java.io.Serializable {

	private int id;
	private String documentName;
	private String documentPath;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date modifiedDate;

	public AcxDocumentMaster() {
	}

	public AcxDocumentMaster(int id, String documentName, String documentPath,
			String createdBy) {
		this.id = id;
		this.documentName = documentName;
		this.documentPath = documentPath;
		this.createdBy = createdBy;
	}

	public AcxDocumentMaster(int id, String documentName, String documentPath,
			String createdBy, Date createdDate, String modifiedBy,
			Date modifiedDate) {
		this.id = id;
		this.documentName = documentName;
		this.documentPath = documentPath;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDocumentName() {
		return this.documentName;
	}

	public void setDocumentName(String documentName) {
		this.documentName = documentName;
	}

	public String getDocumentPath() {
		return this.documentPath;
	}

	public void setDocumentPath(String documentPath) {
		this.documentPath = documentPath;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
