package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AcxExams generated by hbm2java
 */
public class AcxExams implements java.io.Serializable {

	private int id;
	private String examName;
	private Date examStartDate;
	private Date examEndDate;
	private int schoolId;

	public AcxExams() {
	}

	public AcxExams(int id, String examName, int schoolId) {
		this.id = id;
		this.examName = examName;
		this.schoolId = schoolId;
	}

	public AcxExams(int id, String examName, Date examStartDate,
			Date examEndDate, int schoolId) {
		this.id = id;
		this.examName = examName;
		this.examStartDate = examStartDate;
		this.examEndDate = examEndDate;
		this.schoolId = schoolId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getExamName() {
		return this.examName;
	}

	public void setExamName(String examName) {
		this.examName = examName;
	}

	public Date getExamStartDate() {
		return this.examStartDate;
	}

	public void setExamStartDate(Date examStartDate) {
		this.examStartDate = examStartDate;
	}

	public Date getExamEndDate() {
		return this.examEndDate;
	}

	public void setExamEndDate(Date examEndDate) {
		this.examEndDate = examEndDate;
	}

	public int getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(int schoolId) {
		this.schoolId = schoolId;
	}

}
