package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

/**
 * AcxExamSeatingArrangement generated by hbm2java
 */
public class AcxExamSeatingArrangement implements java.io.Serializable {

	private int id;
	private int examId;
	private String studentId;
	private String hallNo;

	public AcxExamSeatingArrangement() {
	}

	public AcxExamSeatingArrangement(int id, int examId, String studentId,
			String hallNo) {
		this.id = id;
		this.examId = examId;
		this.studentId = studentId;
		this.hallNo = hallNo;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getExamId() {
		return this.examId;
	}

	public void setExamId(int examId) {
		this.examId = examId;
	}

	public String getStudentId() {
		return this.studentId;
	}

	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	public String getHallNo() {
		return this.hallNo;
	}

	public void setHallNo(String hallNo) {
		this.hallNo = hallNo;
	}

}
