package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxExamResult generated by hbm2java
 */
@Entity
@Table(name = "acx_exam_result")
public class AcxExamResult implements java.io.Serializable {

	private int id;
	private AcxExams acxExams;
	private AcxSubjectMaster acxSubjectMaster;
	private AcxUsers acxUsersByStudentId;
	private AcxUsers acxUsersByExaminorId;
	private Integer totalMarks;
	private Integer marksObtained;
	private String gradeObtained;
	private BigDecimal percentage;
	private String result;
	private String remarks;

	public AcxExamResult() {
	}

	public AcxExamResult(int id, AcxExams acxExams,
			AcxSubjectMaster acxSubjectMaster, AcxUsers acxUsersByStudentId,
			AcxUsers acxUsersByExaminorId) {
		this.id = id;
		this.acxExams = acxExams;
		this.acxSubjectMaster = acxSubjectMaster;
		this.acxUsersByStudentId = acxUsersByStudentId;
		this.acxUsersByExaminorId = acxUsersByExaminorId;
	}

	public AcxExamResult(int id, AcxExams acxExams,
			AcxSubjectMaster acxSubjectMaster, AcxUsers acxUsersByStudentId,
			AcxUsers acxUsersByExaminorId, Integer totalMarks,
			Integer marksObtained, String gradeObtained, BigDecimal percentage,
			String result, String remarks) {
		this.id = id;
		this.acxExams = acxExams;
		this.acxSubjectMaster = acxSubjectMaster;
		this.acxUsersByStudentId = acxUsersByStudentId;
		this.acxUsersByExaminorId = acxUsersByExaminorId;
		this.totalMarks = totalMarks;
		this.marksObtained = marksObtained;
		this.gradeObtained = gradeObtained;
		this.percentage = percentage;
		this.result = result;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "exam_id", nullable = false)
	public AcxExams getAcxExams() {
		return this.acxExams;
	}

	public void setAcxExams(AcxExams acxExams) {
		this.acxExams = acxExams;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_id", nullable = false)
	public AcxSubjectMaster getAcxSubjectMaster() {
		return this.acxSubjectMaster;
	}

	public void setAcxSubjectMaster(AcxSubjectMaster acxSubjectMaster) {
		this.acxSubjectMaster = acxSubjectMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id", nullable = false)
	public AcxUsers getAcxUsersByStudentId() {
		return this.acxUsersByStudentId;
	}

	public void setAcxUsersByStudentId(AcxUsers acxUsersByStudentId) {
		this.acxUsersByStudentId = acxUsersByStudentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "examinor_id", nullable = false)
	public AcxUsers getAcxUsersByExaminorId() {
		return this.acxUsersByExaminorId;
	}

	public void setAcxUsersByExaminorId(AcxUsers acxUsersByExaminorId) {
		this.acxUsersByExaminorId = acxUsersByExaminorId;
	}

	@Column(name = "total_marks")
	public Integer getTotalMarks() {
		return this.totalMarks;
	}

	public void setTotalMarks(Integer totalMarks) {
		this.totalMarks = totalMarks;
	}

	@Column(name = "marks_obtained")
	public Integer getMarksObtained() {
		return this.marksObtained;
	}

	public void setMarksObtained(Integer marksObtained) {
		this.marksObtained = marksObtained;
	}

	@Column(name = "grade_obtained", length = 45)
	public String getGradeObtained() {
		return this.gradeObtained;
	}

	public void setGradeObtained(String gradeObtained) {
		this.gradeObtained = gradeObtained;
	}

	@Column(name = "percentage", precision = 2)
	public BigDecimal getPercentage() {
		return this.percentage;
	}

	public void setPercentage(BigDecimal percentage) {
		this.percentage = percentage;
	}

	@Column(name = "result", length = 45)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Column(name = "remarks", length = 100)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
