package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AcxExamSchedule generated by hbm2java
 */
public class AcxExamSchedule implements java.io.Serializable {

	private int id;
	private int examId;
	private int classId;
	private int subjectId;
	private Date date;
	private Date startTime;
	private Date endTime;
	private String examinorId;

	public AcxExamSchedule() {
	}

	public AcxExamSchedule(int id, int examId, int classId, int subjectId,
			Date date, String examinorId) {
		this.id = id;
		this.examId = examId;
		this.classId = classId;
		this.subjectId = subjectId;
		this.date = date;
		this.examinorId = examinorId;
	}

	public AcxExamSchedule(int id, int examId, int classId, int subjectId,
			Date date, Date startTime, Date endTime, String examinorId) {
		this.id = id;
		this.examId = examId;
		this.classId = classId;
		this.subjectId = subjectId;
		this.date = date;
		this.startTime = startTime;
		this.endTime = endTime;
		this.examinorId = examinorId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getExamId() {
		return this.examId;
	}

	public void setExamId(int examId) {
		this.examId = examId;
	}

	public int getClassId() {
		return this.classId;
	}

	public void setClassId(int classId) {
		this.classId = classId;
	}

	public int getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(int subjectId) {
		this.subjectId = subjectId;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getExaminorId() {
		return this.examinorId;
	}

	public void setExaminorId(String examinorId) {
		this.examinorId = examinorId;
	}

}
