package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxExamSeatingArrangement generated by hbm2java
 */
@Entity
@Table(name = "acx_exam_seating_arrangement")
public class AcxExamSeatingArrangement implements java.io.Serializable {

	private int id;
	private AcxExams acxExams;
	private AcxUsers acxUsers;
	private String hallNo;

	public AcxExamSeatingArrangement() {
	}

	public AcxExamSeatingArrangement(int id, AcxExams acxExams,
			AcxUsers acxUsers, String hallNo) {
		this.id = id;
		this.acxExams = acxExams;
		this.acxUsers = acxUsers;
		this.hallNo = hallNo;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "exam_id", nullable = false)
	public AcxExams getAcxExams() {
		return this.acxExams;
	}

	public void setAcxExams(AcxExams acxExams) {
		this.acxExams = acxExams;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id", nullable = false)
	public AcxUsers getAcxUsers() {
		return this.acxUsers;
	}

	public void setAcxUsers(AcxUsers acxUsers) {
		this.acxUsers = acxUsers;
	}

	@Column(name = "hall_no", nullable = false, length = 45)
	public String getHallNo() {
		return this.hallNo;
	}

	public void setHallNo(String hallNo) {
		this.hallNo = hallNo;
	}

}
