package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AcxExamSchedule generated by hbm2java
 */
@Entity
@Table(name = "acx_exam_schedule")
public class AcxExamSchedule implements java.io.Serializable {

	private int id;
	private AcxClassMaster acxClassMaster;
	private AcxExams acxExams;
	private AcxSubjectMaster acxSubjectMaster;
	private AcxUsers acxUsers;
	private Date date;
	private Date startTime;
	private Date endTime;

	public AcxExamSchedule() {
	}

	public AcxExamSchedule(int id, AcxClassMaster acxClassMaster,
			AcxExams acxExams, AcxSubjectMaster acxSubjectMaster,
			AcxUsers acxUsers, Date date) {
		this.id = id;
		this.acxClassMaster = acxClassMaster;
		this.acxExams = acxExams;
		this.acxSubjectMaster = acxSubjectMaster;
		this.acxUsers = acxUsers;
		this.date = date;
	}

	public AcxExamSchedule(int id, AcxClassMaster acxClassMaster,
			AcxExams acxExams, AcxSubjectMaster acxSubjectMaster,
			AcxUsers acxUsers, Date date, Date startTime, Date endTime) {
		this.id = id;
		this.acxClassMaster = acxClassMaster;
		this.acxExams = acxExams;
		this.acxSubjectMaster = acxSubjectMaster;
		this.acxUsers = acxUsers;
		this.date = date;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id", nullable = false)
	public AcxClassMaster getAcxClassMaster() {
		return this.acxClassMaster;
	}

	public void setAcxClassMaster(AcxClassMaster acxClassMaster) {
		this.acxClassMaster = acxClassMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "exam_id", nullable = false)
	public AcxExams getAcxExams() {
		return this.acxExams;
	}

	public void setAcxExams(AcxExams acxExams) {
		this.acxExams = acxExams;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_id", nullable = false)
	public AcxSubjectMaster getAcxSubjectMaster() {
		return this.acxSubjectMaster;
	}

	public void setAcxSubjectMaster(AcxSubjectMaster acxSubjectMaster) {
		this.acxSubjectMaster = acxSubjectMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "examinor_id", nullable = false)
	public AcxUsers getAcxUsers() {
		return this.acxUsers;
	}

	public void setAcxUsers(AcxUsers acxUsers) {
		this.acxUsers = acxUsers;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_time", length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

}
