package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * AcxExamResult generated by hbm2java
 */
public class AcxExamResult implements java.io.Serializable {

	private int id;
	private String examinorId;
	private String studentId;
	private int examId;
	private int subjectId;
	private Integer totalMarks;
	private Integer marksObtained;
	private String gradeObtained;
	private BigDecimal percentage;
	private String result;
	private String remarks;

	public AcxExamResult() {
	}

	public AcxExamResult(int id, String examinorId, String studentId,
			int examId, int subjectId) {
		this.id = id;
		this.examinorId = examinorId;
		this.studentId = studentId;
		this.examId = examId;
		this.subjectId = subjectId;
	}

	public AcxExamResult(int id, String examinorId, String studentId,
			int examId, int subjectId, Integer totalMarks,
			Integer marksObtained, String gradeObtained, BigDecimal percentage,
			String result, String remarks) {
		this.id = id;
		this.examinorId = examinorId;
		this.studentId = studentId;
		this.examId = examId;
		this.subjectId = subjectId;
		this.totalMarks = totalMarks;
		this.marksObtained = marksObtained;
		this.gradeObtained = gradeObtained;
		this.percentage = percentage;
		this.result = result;
		this.remarks = remarks;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getExaminorId() {
		return this.examinorId;
	}

	public void setExaminorId(String examinorId) {
		this.examinorId = examinorId;
	}

	public String getStudentId() {
		return this.studentId;
	}

	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	public int getExamId() {
		return this.examId;
	}

	public void setExamId(int examId) {
		this.examId = examId;
	}

	public int getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(int subjectId) {
		this.subjectId = subjectId;
	}

	public Integer getTotalMarks() {
		return this.totalMarks;
	}

	public void setTotalMarks(Integer totalMarks) {
		this.totalMarks = totalMarks;
	}

	public Integer getMarksObtained() {
		return this.marksObtained;
	}

	public void setMarksObtained(Integer marksObtained) {
		this.marksObtained = marksObtained;
	}

	public String getGradeObtained() {
		return this.gradeObtained;
	}

	public void setGradeObtained(String gradeObtained) {
		this.gradeObtained = gradeObtained;
	}

	public BigDecimal getPercentage() {
		return this.percentage;
	}

	public void setPercentage(BigDecimal percentage) {
		this.percentage = percentage;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
