package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

/**
 * AcxFeesMaster generated by hbm2java
 */
public class AcxFeesMaster implements java.io.Serializable {

	private int id;
	private String title;
	private int fees;

	public AcxFeesMaster() {
	}

	public AcxFeesMaster(int id, String title, int fees) {
		this.id = id;
		this.title = title;
		this.fees = fees;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public int getFees() {
		return this.fees;
	}

	public void setFees(int fees) {
		this.fees = fees;
	}

}
