package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AcxMeetings generated by hbm2java
 */
@Entity
@Table(name = "acx_meetings")
public class AcxMeetings implements java.io.Serializable {

	private int id;
	private AcxMeetingTypes acxMeetingTypes;
	private AcxSchoolMaster acxSchoolMaster;
	private AcxStatusMaster acxStatusMaster;
	private Date meetingDay;
	private String moms;
	private Set<AcxMeetingParticipents> acxMeetingParticipentses = new HashSet<AcxMeetingParticipents>(
			0);

	public AcxMeetings() {
	}

	public AcxMeetings(int id, AcxMeetingTypes acxMeetingTypes,
			AcxSchoolMaster acxSchoolMaster, AcxStatusMaster acxStatusMaster) {
		this.id = id;
		this.acxMeetingTypes = acxMeetingTypes;
		this.acxSchoolMaster = acxSchoolMaster;
		this.acxStatusMaster = acxStatusMaster;
	}

	public AcxMeetings(int id, AcxMeetingTypes acxMeetingTypes,
			AcxSchoolMaster acxSchoolMaster, AcxStatusMaster acxStatusMaster,
			Date meetingDay, String moms,
			Set<AcxMeetingParticipents> acxMeetingParticipentses) {
		this.id = id;
		this.acxMeetingTypes = acxMeetingTypes;
		this.acxSchoolMaster = acxSchoolMaster;
		this.acxStatusMaster = acxStatusMaster;
		this.meetingDay = meetingDay;
		this.moms = moms;
		this.acxMeetingParticipentses = acxMeetingParticipentses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "meeting_type", nullable = false)
	public AcxMeetingTypes getAcxMeetingTypes() {
		return this.acxMeetingTypes;
	}

	public void setAcxMeetingTypes(AcxMeetingTypes acxMeetingTypes) {
		this.acxMeetingTypes = acxMeetingTypes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id", nullable = false)
	public AcxSchoolMaster getAcxSchoolMaster() {
		return this.acxSchoolMaster;
	}

	public void setAcxSchoolMaster(AcxSchoolMaster acxSchoolMaster) {
		this.acxSchoolMaster = acxSchoolMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "meeting_status", nullable = false)
	public AcxStatusMaster getAcxStatusMaster() {
		return this.acxStatusMaster;
	}

	public void setAcxStatusMaster(AcxStatusMaster acxStatusMaster) {
		this.acxStatusMaster = acxStatusMaster;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "meeting_day", length = 19)
	public Date getMeetingDay() {
		return this.meetingDay;
	}

	public void setMeetingDay(Date meetingDay) {
		this.meetingDay = meetingDay;
	}

	@Column(name = "moms", length = 1000)
	public String getMoms() {
		return this.moms;
	}

	public void setMoms(String moms) {
		this.moms = moms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxMeetings")
	public Set<AcxMeetingParticipents> getAcxMeetingParticipentses() {
		return this.acxMeetingParticipentses;
	}

	public void setAcxMeetingParticipentses(
			Set<AcxMeetingParticipents> acxMeetingParticipentses) {
		this.acxMeetingParticipentses = acxMeetingParticipentses;
	}

}
