package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

/**
 * AcxMeetingParticipents generated by hbm2java
 */
public class AcxMeetingParticipents implements java.io.Serializable {

	private int id;
	private int meetingId;
	private String participantId;

	public AcxMeetingParticipents() {
	}

	public AcxMeetingParticipents(int id, int meetingId, String participantId) {
		this.id = id;
		this.meetingId = meetingId;
		this.participantId = participantId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getMeetingId() {
		return this.meetingId;
	}

	public void setMeetingId(int meetingId) {
		this.meetingId = meetingId;
	}

	public String getParticipantId() {
		return this.participantId;
	}

	public void setParticipantId(String participantId) {
		this.participantId = participantId;
	}

}
