package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxMeetingParticipents generated by hbm2java
 */
@Entity
@Table(name = "acx_meeting_participents")
public class AcxMeetingParticipents implements java.io.Serializable {

	private int id;
	private AcxMeetings acxMeetings;
	private AcxUsers acxUsers;

	public AcxMeetingParticipents() {
	}

	public AcxMeetingParticipents(int id, AcxMeetings acxMeetings,
			AcxUsers acxUsers) {
		this.id = id;
		this.acxMeetings = acxMeetings;
		this.acxUsers = acxUsers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "meeting_id", nullable = false)
	public AcxMeetings getAcxMeetings() {
		return this.acxMeetings;
	}

	public void setAcxMeetings(AcxMeetings acxMeetings) {
		this.acxMeetings = acxMeetings;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "participant_id", nullable = false)
	public AcxUsers getAcxUsers() {
		return this.acxUsers;
	}

	public void setAcxUsers(AcxUsers acxUsers) {
		this.acxUsers = acxUsers;
	}

}
