package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AcxMeetings generated by hbm2java
 */
public class AcxMeetings implements java.io.Serializable {

	private int id;
	private int schoolId;
	private int meetingType;
	private Date meetingDay;
	private int meetingStatus;
	private String moms;

	public AcxMeetings() {
	}

	public AcxMeetings(int id, int schoolId, int meetingType, int meetingStatus) {
		this.id = id;
		this.schoolId = schoolId;
		this.meetingType = meetingType;
		this.meetingStatus = meetingStatus;
	}

	public AcxMeetings(int id, int schoolId, int meetingType, Date meetingDay,
			int meetingStatus, String moms) {
		this.id = id;
		this.schoolId = schoolId;
		this.meetingType = meetingType;
		this.meetingDay = meetingDay;
		this.meetingStatus = meetingStatus;
		this.moms = moms;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(int schoolId) {
		this.schoolId = schoolId;
	}

	public int getMeetingType() {
		return this.meetingType;
	}

	public void setMeetingType(int meetingType) {
		this.meetingType = meetingType;
	}

	public Date getMeetingDay() {
		return this.meetingDay;
	}

	public void setMeetingDay(Date meetingDay) {
		this.meetingDay = meetingDay;
	}

	public int getMeetingStatus() {
		return this.meetingStatus;
	}

	public void setMeetingStatus(int meetingStatus) {
		this.meetingStatus = meetingStatus;
	}

	public String getMoms() {
		return this.moms;
	}

	public void setMoms(String moms) {
		this.moms = moms;
	}

}
