package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

/**
 * AcxNoticeTypes generated by hbm2java
 */
public class AcxNoticeTypes implements java.io.Serializable {

	private int id;
	private String title;

	public AcxNoticeTypes() {
	}

	public AcxNoticeTypes(int id) {
		this.id = id;
	}

	public AcxNoticeTypes(int id, String title) {
		this.id = id;
		this.title = title;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
