package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AcxNotices generated by hbm2java
 */
public class AcxNotices implements java.io.Serializable {

	private int id;
	private int schoolId;
	private int noticeType;
	private Integer classId;
	private String notice;
	private Date startDate;
	private Date endDate;
	private String issuerId;

	public AcxNotices() {
	}

	public AcxNotices(int id, int schoolId, int noticeType, String notice,
			String issuerId) {
		this.id = id;
		this.schoolId = schoolId;
		this.noticeType = noticeType;
		this.notice = notice;
		this.issuerId = issuerId;
	}

	public AcxNotices(int id, int schoolId, int noticeType, Integer classId,
			String notice, Date startDate, Date endDate, String issuerId) {
		this.id = id;
		this.schoolId = schoolId;
		this.noticeType = noticeType;
		this.classId = classId;
		this.notice = notice;
		this.startDate = startDate;
		this.endDate = endDate;
		this.issuerId = issuerId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(int schoolId) {
		this.schoolId = schoolId;
	}

	public int getNoticeType() {
		return this.noticeType;
	}

	public void setNoticeType(int noticeType) {
		this.noticeType = noticeType;
	}

	public Integer getClassId() {
		return this.classId;
	}

	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	public String getNotice() {
		return this.notice;
	}

	public void setNotice(String notice) {
		this.notice = notice;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getIssuerId() {
		return this.issuerId;
	}

	public void setIssuerId(String issuerId) {
		this.issuerId = issuerId;
	}

}
