package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AcxNotices generated by hbm2java
 */
@Entity
@Table(name = "acx_notices")
public class AcxNotices implements java.io.Serializable {

	private int id;
	private AcxClassMaster acxClassMaster;
	private AcxNoticeTypes acxNoticeTypes;
	private AcxSchoolMaster acxSchoolMaster;
	private AcxUsers acxUsers;
	private String notice;
	private Date startDate;
	private Date endDate;

	public AcxNotices() {
	}

	public AcxNotices(int id, AcxNoticeTypes acxNoticeTypes,
			AcxSchoolMaster acxSchoolMaster, AcxUsers acxUsers, String notice) {
		this.id = id;
		this.acxNoticeTypes = acxNoticeTypes;
		this.acxSchoolMaster = acxSchoolMaster;
		this.acxUsers = acxUsers;
		this.notice = notice;
	}

	public AcxNotices(int id, AcxClassMaster acxClassMaster,
			AcxNoticeTypes acxNoticeTypes, AcxSchoolMaster acxSchoolMaster,
			AcxUsers acxUsers, String notice, Date startDate, Date endDate) {
		this.id = id;
		this.acxClassMaster = acxClassMaster;
		this.acxNoticeTypes = acxNoticeTypes;
		this.acxSchoolMaster = acxSchoolMaster;
		this.acxUsers = acxUsers;
		this.notice = notice;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id")
	public AcxClassMaster getAcxClassMaster() {
		return this.acxClassMaster;
	}

	public void setAcxClassMaster(AcxClassMaster acxClassMaster) {
		this.acxClassMaster = acxClassMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "notice_type", nullable = false)
	public AcxNoticeTypes getAcxNoticeTypes() {
		return this.acxNoticeTypes;
	}

	public void setAcxNoticeTypes(AcxNoticeTypes acxNoticeTypes) {
		this.acxNoticeTypes = acxNoticeTypes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id", nullable = false)
	public AcxSchoolMaster getAcxSchoolMaster() {
		return this.acxSchoolMaster;
	}

	public void setAcxSchoolMaster(AcxSchoolMaster acxSchoolMaster) {
		this.acxSchoolMaster = acxSchoolMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "issuer_id", nullable = false)
	public AcxUsers getAcxUsers() {
		return this.acxUsers;
	}

	public void setAcxUsers(AcxUsers acxUsers) {
		this.acxUsers = acxUsers;
	}

	@Column(name = "notice", nullable = false, length = 1000)
	public String getNotice() {
		return this.notice;
	}

	public void setNotice(String notice) {
		this.notice = notice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
