package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AcxOnlinePoll generated by hbm2java
 */
public class AcxOnlinePoll implements java.io.Serializable {

	private int id;
	private int schoolId;
	private String topic;
	private Date startDate;
	private String endDate;
	private String issuerId;

	public AcxOnlinePoll() {
	}

	public AcxOnlinePoll(int id, int schoolId, String topic, String endDate,
			String issuerId) {
		this.id = id;
		this.schoolId = schoolId;
		this.topic = topic;
		this.endDate = endDate;
		this.issuerId = issuerId;
	}

	public AcxOnlinePoll(int id, int schoolId, String topic, Date startDate,
			String endDate, String issuerId) {
		this.id = id;
		this.schoolId = schoolId;
		this.topic = topic;
		this.startDate = startDate;
		this.endDate = endDate;
		this.issuerId = issuerId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(int schoolId) {
		this.schoolId = schoolId;
	}

	public String getTopic() {
		return this.topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getIssuerId() {
		return this.issuerId;
	}

	public void setIssuerId(String issuerId) {
		this.issuerId = issuerId;
	}

}
