package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AcxOnlinePoll generated by hbm2java
 */
@Entity
@Table(name = "acx_online_poll")
public class AcxOnlinePoll implements java.io.Serializable {

	private int id;
	private AcxSchoolMaster acxSchoolMaster;
	private AcxUsers acxUsers;
	private String topic;
	private Date startDate;
	private String endDate;
	private Set<AcxPollVoters> acxPollVoterses = new HashSet<AcxPollVoters>(0);
	private Set<AcxPollResults> acxPollResultses = new HashSet<AcxPollResults>(
			0);

	public AcxOnlinePoll() {
	}

	public AcxOnlinePoll(int id, AcxSchoolMaster acxSchoolMaster,
			AcxUsers acxUsers, String topic, String endDate) {
		this.id = id;
		this.acxSchoolMaster = acxSchoolMaster;
		this.acxUsers = acxUsers;
		this.topic = topic;
		this.endDate = endDate;
	}

	public AcxOnlinePoll(int id, AcxSchoolMaster acxSchoolMaster,
			AcxUsers acxUsers, String topic, Date startDate, String endDate,
			Set<AcxPollVoters> acxPollVoterses,
			Set<AcxPollResults> acxPollResultses) {
		this.id = id;
		this.acxSchoolMaster = acxSchoolMaster;
		this.acxUsers = acxUsers;
		this.topic = topic;
		this.startDate = startDate;
		this.endDate = endDate;
		this.acxPollVoterses = acxPollVoterses;
		this.acxPollResultses = acxPollResultses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id", nullable = false)
	public AcxSchoolMaster getAcxSchoolMaster() {
		return this.acxSchoolMaster;
	}

	public void setAcxSchoolMaster(AcxSchoolMaster acxSchoolMaster) {
		this.acxSchoolMaster = acxSchoolMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "issuer_id", nullable = false)
	public AcxUsers getAcxUsers() {
		return this.acxUsers;
	}

	public void setAcxUsers(AcxUsers acxUsers) {
		this.acxUsers = acxUsers;
	}

	@Column(name = "topic", nullable = false)
	public String getTopic() {
		return this.topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "end_date", nullable = false, length = 45)
	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxOnlinePoll")
	public Set<AcxPollVoters> getAcxPollVoterses() {
		return this.acxPollVoterses;
	}

	public void setAcxPollVoterses(Set<AcxPollVoters> acxPollVoterses) {
		this.acxPollVoterses = acxPollVoterses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxOnlinePoll")
	public Set<AcxPollResults> getAcxPollResultses() {
		return this.acxPollResultses;
	}

	public void setAcxPollResultses(Set<AcxPollResults> acxPollResultses) {
		this.acxPollResultses = acxPollResultses;
	}

}
