package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * AcxParentInfo generated by hbm2java
 */
public class AcxParentInfo implements java.io.Serializable {

	private int id;
	private String parentId;
	private String occupation;
	private String qualification;
	private BigDecimal annualIncome;
	private String relationWirhStudent;

	public AcxParentInfo() {
	}

	public AcxParentInfo(int id, String parentId) {
		this.id = id;
		this.parentId = parentId;
	}

	public AcxParentInfo(int id, String parentId, String occupation,
			String qualification, BigDecimal annualIncome,
			String relationWirhStudent) {
		this.id = id;
		this.parentId = parentId;
		this.occupation = occupation;
		this.qualification = qualification;
		this.annualIncome = annualIncome;
		this.relationWirhStudent = relationWirhStudent;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

	public BigDecimal getAnnualIncome() {
		return this.annualIncome;
	}

	public void setAnnualIncome(BigDecimal annualIncome) {
		this.annualIncome = annualIncome;
	}

	public String getRelationWirhStudent() {
		return this.relationWirhStudent;
	}

	public void setRelationWirhStudent(String relationWirhStudent) {
		this.relationWirhStudent = relationWirhStudent;
	}

}
