package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

/**
 * AcxPollResults generated by hbm2java
 */
public class AcxPollResults implements java.io.Serializable {

	private int id;
	private int pollId;
	private String answer;
	private int numberOfVotes;

	public AcxPollResults() {
	}

	public AcxPollResults(int id, int pollId, String answer, int numberOfVotes) {
		this.id = id;
		this.pollId = pollId;
		this.answer = answer;
		this.numberOfVotes = numberOfVotes;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getPollId() {
		return this.pollId;
	}

	public void setPollId(int pollId) {
		this.pollId = pollId;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public int getNumberOfVotes() {
		return this.numberOfVotes;
	}

	public void setNumberOfVotes(int numberOfVotes) {
		this.numberOfVotes = numberOfVotes;
	}

}
