package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

/**
 * AcxParentChild generated by hbm2java
 */
public class AcxParentChild implements java.io.Serializable {

	private int id;
	private String parentId;
	private String childId;

	public AcxParentChild() {
	}

	public AcxParentChild(int id, String parentId, String childId) {
		this.id = id;
		this.parentId = parentId;
		this.childId = childId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getChildId() {
		return this.childId;
	}

	public void setChildId(String childId) {
		this.childId = childId;
	}

}
