package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxParentChild generated by hbm2java
 */
@Entity
@Table(name = "acx_parent_child")
public class AcxParentChild implements java.io.Serializable {

	private int id;
	private AcxUsers acxUsersByParentId;
	private AcxUsers acxUsersByChildId;

	public AcxParentChild() {
	}

	public AcxParentChild(int id, AcxUsers acxUsersByParentId,
			AcxUsers acxUsersByChildId) {
		this.id = id;
		this.acxUsersByParentId = acxUsersByParentId;
		this.acxUsersByChildId = acxUsersByChildId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id", nullable = false)
	public AcxUsers getAcxUsersByParentId() {
		return this.acxUsersByParentId;
	}

	public void setAcxUsersByParentId(AcxUsers acxUsersByParentId) {
		this.acxUsersByParentId = acxUsersByParentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "child_id", nullable = false)
	public AcxUsers getAcxUsersByChildId() {
		return this.acxUsersByChildId;
	}

	public void setAcxUsersByChildId(AcxUsers acxUsersByChildId) {
		this.acxUsersByChildId = acxUsersByChildId;
	}

}
