package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

/**
 * AcxPollVoters generated by hbm2java
 */
public class AcxPollVoters implements java.io.Serializable {

	private int id;
	private int pollId;
	private String voterId;

	public AcxPollVoters() {
	}

	public AcxPollVoters(int id, int pollId, String voterId) {
		this.id = id;
		this.pollId = pollId;
		this.voterId = voterId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getPollId() {
		return this.pollId;
	}

	public void setPollId(int pollId) {
		this.pollId = pollId;
	}

	public String getVoterId() {
		return this.voterId;
	}

	public void setVoterId(String voterId) {
		this.voterId = voterId;
	}

}
