package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AcxSchoolMaster generated by hbm2java
 */
@Entity
@Table(name = "acx_school_master", uniqueConstraints = {
		@UniqueConstraint(columnNames = "phone_no"),
		@UniqueConstraint(columnNames = "email_id") })
public class AcxSchoolMaster implements java.io.Serializable {

	private int id;
	private String name;
	private String address;
	private String phoneNo;
	private String emailId;
	private Set<AcxNotices> acxNoticeses = new HashSet<AcxNotices>(0);
	private Set<AcxOnlinePoll> acxOnlinePolls = new HashSet<AcxOnlinePoll>(0);
	private Set<AcxUsers> acxUserses = new HashSet<AcxUsers>(0);
	private Set<AcxAttendance> acxAttendances = new HashSet<AcxAttendance>(0);
	private Set<AcxMeetings> acxMeetingses = new HashSet<AcxMeetings>(0);
	private Set<AcxClassMaster> acxClassMasters = new HashSet<AcxClassMaster>(0);
	private Set<AcxExams> acxExamses = new HashSet<AcxExams>(0);

	public AcxSchoolMaster() {
	}

	public AcxSchoolMaster(int id, String name, String address, String phoneNo,
			String emailId) {
		this.id = id;
		this.name = name;
		this.address = address;
		this.phoneNo = phoneNo;
		this.emailId = emailId;
	}

	public AcxSchoolMaster(int id, String name, String address, String phoneNo,
			String emailId, Set<AcxNotices> acxNoticeses,
			Set<AcxOnlinePoll> acxOnlinePolls, Set<AcxUsers> acxUserses,
			Set<AcxAttendance> acxAttendances, Set<AcxMeetings> acxMeetingses,
			Set<AcxClassMaster> acxClassMasters, Set<AcxExams> acxExamses) {
		this.id = id;
		this.name = name;
		this.address = address;
		this.phoneNo = phoneNo;
		this.emailId = emailId;
		this.acxNoticeses = acxNoticeses;
		this.acxOnlinePolls = acxOnlinePolls;
		this.acxUserses = acxUserses;
		this.acxAttendances = acxAttendances;
		this.acxMeetingses = acxMeetingses;
		this.acxClassMasters = acxClassMasters;
		this.acxExamses = acxExamses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone_no", unique = true, nullable = false, length = 45)
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Column(name = "email_id", unique = true, nullable = false, length = 45)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSchoolMaster")
	public Set<AcxNotices> getAcxNoticeses() {
		return this.acxNoticeses;
	}

	public void setAcxNoticeses(Set<AcxNotices> acxNoticeses) {
		this.acxNoticeses = acxNoticeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSchoolMaster")
	public Set<AcxOnlinePoll> getAcxOnlinePolls() {
		return this.acxOnlinePolls;
	}

	public void setAcxOnlinePolls(Set<AcxOnlinePoll> acxOnlinePolls) {
		this.acxOnlinePolls = acxOnlinePolls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSchoolMaster")
	public Set<AcxUsers> getAcxUserses() {
		return this.acxUserses;
	}

	public void setAcxUserses(Set<AcxUsers> acxUserses) {
		this.acxUserses = acxUserses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSchoolMaster")
	public Set<AcxAttendance> getAcxAttendances() {
		return this.acxAttendances;
	}

	public void setAcxAttendances(Set<AcxAttendance> acxAttendances) {
		this.acxAttendances = acxAttendances;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSchoolMaster")
	public Set<AcxMeetings> getAcxMeetingses() {
		return this.acxMeetingses;
	}

	public void setAcxMeetingses(Set<AcxMeetings> acxMeetingses) {
		this.acxMeetingses = acxMeetingses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSchoolMaster")
	public Set<AcxClassMaster> getAcxClassMasters() {
		return this.acxClassMasters;
	}

	public void setAcxClassMasters(Set<AcxClassMaster> acxClassMasters) {
		this.acxClassMasters = acxClassMasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSchoolMaster")
	public Set<AcxExams> getAcxExamses() {
		return this.acxExamses;
	}

	public void setAcxExamses(Set<AcxExams> acxExamses) {
		this.acxExamses = acxExamses;
	}

}
