package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AcxStudentHealth generated by hbm2java
 */
public class AcxStudentHealth implements java.io.Serializable {

	private int id;
	private String studentId;
	private Date day;
	private int height;
	private int weight;
	private String healthRemarks;

	public AcxStudentHealth() {
	}

	public AcxStudentHealth(int id, String studentId, int height, int weight) {
		this.id = id;
		this.studentId = studentId;
		this.height = height;
		this.weight = weight;
	}

	public AcxStudentHealth(int id, String studentId, Date day, int height,
			int weight, String healthRemarks) {
		this.id = id;
		this.studentId = studentId;
		this.day = day;
		this.height = height;
		this.weight = weight;
		this.healthRemarks = healthRemarks;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getStudentId() {
		return this.studentId;
	}

	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	public Date getDay() {
		return this.day;
	}

	public void setDay(Date day) {
		this.day = day;
	}

	public int getHeight() {
		return this.height;
	}

	public void setHeight(int height) {
		this.height = height;
	}

	public int getWeight() {
		return this.weight;
	}

	public void setWeight(int weight) {
		this.weight = weight;
	}

	public String getHealthRemarks() {
		return this.healthRemarks;
	}

	public void setHealthRemarks(String healthRemarks) {
		this.healthRemarks = healthRemarks;
	}

}
