package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AcxSubjectMaster generated by hbm2java
 */
@Entity
@Table(name = "acx_subject_master", uniqueConstraints = @UniqueConstraint(columnNames = "title"))
public class AcxSubjectMaster implements java.io.Serializable {

	private int id;
	private String title;
	private Set<AcxTeacherSubjects> acxTeacherSubjectses = new HashSet<AcxTeacherSubjects>(
			0);
	private Set<AcxExamResult> acxExamResults = new HashSet<AcxExamResult>(0);
	private Set<AcxExamSchedule> acxExamSchedules = new HashSet<AcxExamSchedule>(
			0);
	private Set<AcxScheduler> acxSchedulers = new HashSet<AcxScheduler>(0);

	public AcxSubjectMaster() {
	}

	public AcxSubjectMaster(int id, String title) {
		this.id = id;
		this.title = title;
	}

	public AcxSubjectMaster(int id, String title,
			Set<AcxTeacherSubjects> acxTeacherSubjectses,
			Set<AcxExamResult> acxExamResults,
			Set<AcxExamSchedule> acxExamSchedules,
			Set<AcxScheduler> acxSchedulers) {
		this.id = id;
		this.title = title;
		this.acxTeacherSubjectses = acxTeacherSubjectses;
		this.acxExamResults = acxExamResults;
		this.acxExamSchedules = acxExamSchedules;
		this.acxSchedulers = acxSchedulers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "title", unique = true, nullable = false, length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSubjectMaster")
	public Set<AcxTeacherSubjects> getAcxTeacherSubjectses() {
		return this.acxTeacherSubjectses;
	}

	public void setAcxTeacherSubjectses(
			Set<AcxTeacherSubjects> acxTeacherSubjectses) {
		this.acxTeacherSubjectses = acxTeacherSubjectses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSubjectMaster")
	public Set<AcxExamResult> getAcxExamResults() {
		return this.acxExamResults;
	}

	public void setAcxExamResults(Set<AcxExamResult> acxExamResults) {
		this.acxExamResults = acxExamResults;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSubjectMaster")
	public Set<AcxExamSchedule> getAcxExamSchedules() {
		return this.acxExamSchedules;
	}

	public void setAcxExamSchedules(Set<AcxExamSchedule> acxExamSchedules) {
		this.acxExamSchedules = acxExamSchedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxSubjectMaster")
	public Set<AcxScheduler> getAcxSchedulers() {
		return this.acxSchedulers;
	}

	public void setAcxSchedulers(Set<AcxScheduler> acxSchedulers) {
		this.acxSchedulers = acxSchedulers;
	}

}
