package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxStudentInfo generated by hbm2java
 */
@Entity
@Table(name = "acx_student_info")
public class AcxStudentInfo implements java.io.Serializable {

	private int id;
	private AcxClassMaster acxClassMaster;
	private AcxUsers acxUsers;
	private String roleNumber;

	public AcxStudentInfo() {
	}

	public AcxStudentInfo(int id, AcxClassMaster acxClassMaster,
			AcxUsers acxUsers, String roleNumber) {
		this.id = id;
		this.acxClassMaster = acxClassMaster;
		this.acxUsers = acxUsers;
		this.roleNumber = roleNumber;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id", nullable = false)
	public AcxClassMaster getAcxClassMaster() {
		return this.acxClassMaster;
	}

	public void setAcxClassMaster(AcxClassMaster acxClassMaster) {
		this.acxClassMaster = acxClassMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id", nullable = false)
	public AcxUsers getAcxUsers() {
		return this.acxUsers;
	}

	public void setAcxUsers(AcxUsers acxUsers) {
		this.acxUsers = acxUsers;
	}

	@Column(name = "role_number", nullable = false, length = 45)
	public String getRoleNumber() {
		return this.roleNumber;
	}

	public void setRoleNumber(String roleNumber) {
		this.roleNumber = roleNumber;
	}

}
