package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

/**
 * AcxStudentInfo generated by hbm2java
 */
public class AcxStudentInfo implements java.io.Serializable {

	private int id;
	private String studentId;
	private int classId;
	private String roleNumber;

	public AcxStudentInfo() {
	}

	public AcxStudentInfo(int id, String studentId, int classId,
			String roleNumber) {
		this.id = id;
		this.studentId = studentId;
		this.classId = classId;
		this.roleNumber = roleNumber;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getStudentId() {
		return this.studentId;
	}

	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	public int getClassId() {
		return this.classId;
	}

	public void setClassId(int classId) {
		this.classId = classId;
	}

	public String getRoleNumber() {
		return this.roleNumber;
	}

	public void setRoleNumber(String roleNumber) {
		this.roleNumber = roleNumber;
	}

}
