package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

/**
 * AcxStatusMaster generated by hbm2java
 */
public class AcxStatusMaster implements java.io.Serializable {

	private int id;
	private String title;
	private String type;

	public AcxStatusMaster() {
	}

	public AcxStatusMaster(int id, String title, String type) {
		this.id = id;
		this.title = title;
		this.type = type;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
