package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxScheduler generated by hbm2java
 */
@Entity
@Table(name = "acx_scheduler")
public class AcxScheduler implements java.io.Serializable {

	private int id;
	private AcxClassMaster acxClassMaster;
	private AcxSubjectMaster acxSubjectMaster;
	private AcxUsers acxUsers;
	private String day;
	private Integer lectureNo;

	public AcxScheduler() {
	}

	public AcxScheduler(int id, AcxClassMaster acxClassMaster,
			AcxSubjectMaster acxSubjectMaster, AcxUsers acxUsers, String day) {
		this.id = id;
		this.acxClassMaster = acxClassMaster;
		this.acxSubjectMaster = acxSubjectMaster;
		this.acxUsers = acxUsers;
		this.day = day;
	}

	public AcxScheduler(int id, AcxClassMaster acxClassMaster,
			AcxSubjectMaster acxSubjectMaster, AcxUsers acxUsers, String day,
			Integer lectureNo) {
		this.id = id;
		this.acxClassMaster = acxClassMaster;
		this.acxSubjectMaster = acxSubjectMaster;
		this.acxUsers = acxUsers;
		this.day = day;
		this.lectureNo = lectureNo;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id", nullable = false)
	public AcxClassMaster getAcxClassMaster() {
		return this.acxClassMaster;
	}

	public void setAcxClassMaster(AcxClassMaster acxClassMaster) {
		this.acxClassMaster = acxClassMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_id", nullable = false)
	public AcxSubjectMaster getAcxSubjectMaster() {
		return this.acxSubjectMaster;
	}

	public void setAcxSubjectMaster(AcxSubjectMaster acxSubjectMaster) {
		this.acxSubjectMaster = acxSubjectMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teacher_id", nullable = false)
	public AcxUsers getAcxUsers() {
		return this.acxUsers;
	}

	public void setAcxUsers(AcxUsers acxUsers) {
		this.acxUsers = acxUsers;
	}

	@Column(name = "day", nullable = false, length = 45)
	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	@Column(name = "lecture_no")
	public Integer getLectureNo() {
		return this.lectureNo;
	}

	public void setLectureNo(Integer lectureNo) {
		this.lectureNo = lectureNo;
	}

}
