package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

/**
 * AcxScheduler generated by hbm2java
 */
public class AcxScheduler implements java.io.Serializable {

	private int id;
	private int classId;
	private String day;
	private Integer lectureNo;
	private String teacherId;
	private int subjectId;

	public AcxScheduler() {
	}

	public AcxScheduler(int id, int classId, String day, String teacherId,
			int subjectId) {
		this.id = id;
		this.classId = classId;
		this.day = day;
		this.teacherId = teacherId;
		this.subjectId = subjectId;
	}

	public AcxScheduler(int id, int classId, String day, Integer lectureNo,
			String teacherId, int subjectId) {
		this.id = id;
		this.classId = classId;
		this.day = day;
		this.lectureNo = lectureNo;
		this.teacherId = teacherId;
		this.subjectId = subjectId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getClassId() {
		return this.classId;
	}

	public void setClassId(int classId) {
		this.classId = classId;
	}

	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	public Integer getLectureNo() {
		return this.lectureNo;
	}

	public void setLectureNo(Integer lectureNo) {
		this.lectureNo = lectureNo;
	}

	public String getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(String teacherId) {
		this.teacherId = teacherId;
	}

	public int getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(int subjectId) {
		this.subjectId = subjectId;
	}

}
