package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AcxStatusMaster generated by hbm2java
 */
@Entity
@Table(name = "acx_status_master", uniqueConstraints = @UniqueConstraint(columnNames = "title"))
public class AcxStatusMaster implements java.io.Serializable {

	private int id;
	private String title;
	private String type;
	private Set<AcxAdmissionFees> acxAdmissionFeeses = new HashSet<AcxAdmissionFees>(
			0);
	private Set<AcxMeetings> acxMeetingses = new HashSet<AcxMeetings>(0);
	private Set<AcxAdmissionInfo> acxAdmissionInfos = new HashSet<AcxAdmissionInfo>(
			0);

	public AcxStatusMaster() {
	}

	public AcxStatusMaster(int id, String title, String type) {
		this.id = id;
		this.title = title;
		this.type = type;
	}

	public AcxStatusMaster(int id, String title, String type,
			Set<AcxAdmissionFees> acxAdmissionFeeses,
			Set<AcxMeetings> acxMeetingses,
			Set<AcxAdmissionInfo> acxAdmissionInfos) {
		this.id = id;
		this.title = title;
		this.type = type;
		this.acxAdmissionFeeses = acxAdmissionFeeses;
		this.acxMeetingses = acxMeetingses;
		this.acxAdmissionInfos = acxAdmissionInfos;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "title", unique = true, nullable = false, length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxStatusMaster")
	public Set<AcxAdmissionFees> getAcxAdmissionFeeses() {
		return this.acxAdmissionFeeses;
	}

	public void setAcxAdmissionFeeses(Set<AcxAdmissionFees> acxAdmissionFeeses) {
		this.acxAdmissionFeeses = acxAdmissionFeeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxStatusMaster")
	public Set<AcxMeetings> getAcxMeetingses() {
		return this.acxMeetingses;
	}

	public void setAcxMeetingses(Set<AcxMeetings> acxMeetingses) {
		this.acxMeetingses = acxMeetingses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxStatusMaster")
	public Set<AcxAdmissionInfo> getAcxAdmissionInfos() {
		return this.acxAdmissionInfos;
	}

	public void setAcxAdmissionInfos(Set<AcxAdmissionInfo> acxAdmissionInfos) {
		this.acxAdmissionInfos = acxAdmissionInfos;
	}

}
