package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

/**
 * AcxTeacherSubjects generated by hbm2java
 */
public class AcxTeacherSubjects implements java.io.Serializable {

	private int id;
	private String teacherId;
	private int subjectId;

	public AcxTeacherSubjects() {
	}

	public AcxTeacherSubjects(int id, String teacherId, int subjectId) {
		this.id = id;
		this.teacherId = teacherId;
		this.subjectId = subjectId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(String teacherId) {
		this.teacherId = teacherId;
	}

	public int getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(int subjectId) {
		this.subjectId = subjectId;
	}

}
