package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

/**
 * AcxTeacherInfo generated by hbm2java
 */
public class AcxTeacherInfo implements java.io.Serializable {

	private int id;
	private String teacherId;
	private String qualification;

	public AcxTeacherInfo() {
	}

	public AcxTeacherInfo(int id, String teacherId, String qualification) {
		this.id = id;
		this.teacherId = teacherId;
		this.qualification = qualification;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(String teacherId) {
		this.teacherId = teacherId;
	}

	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

}
