package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AcxTeacherNotes generated by hbm2java
 */
public class AcxTeacherNotes implements java.io.Serializable {

	private int id;
	private String teacherId;
	private Date day;
	private String notes;

	public AcxTeacherNotes() {
	}

	public AcxTeacherNotes(int id, String teacherId, String notes) {
		this.id = id;
		this.teacherId = teacherId;
		this.notes = notes;
	}

	public AcxTeacherNotes(int id, String teacherId, Date day, String notes) {
		this.id = id;
		this.teacherId = teacherId;
		this.day = day;
		this.notes = notes;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(String teacherId) {
		this.teacherId = teacherId;
	}

	public Date getDay() {
		return this.day;
	}

	public void setDay(Date day) {
		this.day = day;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
