package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxTeacherSubjects generated by hbm2java
 */
@Entity
@Table(name = "acx_teacher_subjects")
public class AcxTeacherSubjects implements java.io.Serializable {

	private int id;
	private AcxSubjectMaster acxSubjectMaster;
	private AcxUsers acxUsers;

	public AcxTeacherSubjects() {
	}

	public AcxTeacherSubjects(int id, AcxSubjectMaster acxSubjectMaster,
			AcxUsers acxUsers) {
		this.id = id;
		this.acxSubjectMaster = acxSubjectMaster;
		this.acxUsers = acxUsers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_id", nullable = false)
	public AcxSubjectMaster getAcxSubjectMaster() {
		return this.acxSubjectMaster;
	}

	public void setAcxSubjectMaster(AcxSubjectMaster acxSubjectMaster) {
		this.acxSubjectMaster = acxSubjectMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teacher_id", nullable = false)
	public AcxUsers getAcxUsers() {
		return this.acxUsers;
	}

	public void setAcxUsers(AcxUsers acxUsers) {
		this.acxUsers = acxUsers;
	}

}
