package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxTeacherInfo generated by hbm2java
 */
@Entity
@Table(name = "acx_teacher_info")
public class AcxTeacherInfo implements java.io.Serializable {

	private int id;
	private AcxUsers acxUsers;
	private String qualification;

	public AcxTeacherInfo() {
	}

	public AcxTeacherInfo(int id, AcxUsers acxUsers, String qualification) {
		this.id = id;
		this.acxUsers = acxUsers;
		this.qualification = qualification;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teacher_id", nullable = false)
	public AcxUsers getAcxUsers() {
		return this.acxUsers;
	}

	public void setAcxUsers(AcxUsers acxUsers) {
		this.acxUsers = acxUsers;
	}

	@Column(name = "qualification", nullable = false, length = 45)
	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

}
