package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AcxUsers generated by hbm2java
 */
@Entity
@Table(name = "acx_users")
public class AcxUsers implements java.io.Serializable {

	private String userId;
	private AcxSchoolMaster acxSchoolMaster;
	private String password;
	private String name;
	private String address;
	private String contactNo;
	private String emailId;
	private Date birthDate;
	private String sex;
	private Set<AcxAttendance> acxAttendancesForTeacherId = new HashSet<AcxAttendance>(
			0);
	private Set<AcxAttendance> acxAttendancesForStudentId = new HashSet<AcxAttendance>(
			0);
	private Set<AcxUserDocuments> acxUserDocumentses = new HashSet<AcxUserDocuments>(
			0);
	private Set<AcxParentChild> acxParentChildsForParentId = new HashSet<AcxParentChild>(
			0);
	private Set<AcxExamResult> acxExamResultsForStudentId = new HashSet<AcxExamResult>(
			0);
	private Set<AcxExamSeatingArrangement> acxExamSeatingArrangements = new HashSet<AcxExamSeatingArrangement>(
			0);
	private Set<AcxTeacherNotes> acxTeacherNoteses = new HashSet<AcxTeacherNotes>(
			0);
	private Set<AcxExamResult> acxExamResultsForExaminorId = new HashSet<AcxExamResult>(
			0);
	private Set<AcxParentChild> acxParentChildsForChildId = new HashSet<AcxParentChild>(
			0);
	private Set<AcxNotices> acxNoticeses = new HashSet<AcxNotices>(0);
	private Set<AcxParentInfo> acxParentInfos = new HashSet<AcxParentInfo>(0);
	private Set<AcxAdmissionInfo> acxAdmissionInfos = new HashSet<AcxAdmissionInfo>(
			0);
	private Set<AcxUserRoles> acxUserRoleses = new HashSet<AcxUserRoles>(0);
	private Set<AcxPollVoters> acxPollVoterses = new HashSet<AcxPollVoters>(0);
	private Set<AcxScheduler> acxSchedulers = new HashSet<AcxScheduler>(0);
	private Set<AcxDocumentMaster> acxDocumentMastersForModifiedBy = new HashSet<AcxDocumentMaster>(
			0);
	private Set<AcxDocumentMaster> acxDocumentMastersForCreatedBy = new HashSet<AcxDocumentMaster>(
			0);
	private Set<AcxMeetingParticipents> acxMeetingParticipentses = new HashSet<AcxMeetingParticipents>(
			0);
	private Set<AcxOnlinePoll> acxOnlinePolls = new HashSet<AcxOnlinePoll>(0);
	private Set<AcxStudentHealth> acxStudentHealths = new HashSet<AcxStudentHealth>(
			0);
	private Set<AcxExamSchedule> acxExamSchedules = new HashSet<AcxExamSchedule>(
			0);
	private Set<AcxStudentInfo> acxStudentInfos = new HashSet<AcxStudentInfo>(0);
	private Set<AcxTeacherInfo> acxTeacherInfos = new HashSet<AcxTeacherInfo>(0);
	private Set<AcxTeacherSubjects> acxTeacherSubjectses = new HashSet<AcxTeacherSubjects>(
			0);

	public AcxUsers() {
	}

	public AcxUsers(String userId, AcxSchoolMaster acxSchoolMaster,
			String password, String name, String address, String contactNo,
			String emailId) {
		this.userId = userId;
		this.acxSchoolMaster = acxSchoolMaster;
		this.password = password;
		this.name = name;
		this.address = address;
		this.contactNo = contactNo;
		this.emailId = emailId;
	}

	public AcxUsers(String userId, AcxSchoolMaster acxSchoolMaster,
			String password, String name, String address, String contactNo,
			String emailId, Date birthDate, String sex,
			Set<AcxAttendance> acxAttendancesForTeacherId,
			Set<AcxAttendance> acxAttendancesForStudentId,
			Set<AcxUserDocuments> acxUserDocumentses,
			Set<AcxParentChild> acxParentChildsForParentId,
			Set<AcxExamResult> acxExamResultsForStudentId,
			Set<AcxExamSeatingArrangement> acxExamSeatingArrangements,
			Set<AcxTeacherNotes> acxTeacherNoteses,
			Set<AcxExamResult> acxExamResultsForExaminorId,
			Set<AcxParentChild> acxParentChildsForChildId,
			Set<AcxNotices> acxNoticeses, Set<AcxParentInfo> acxParentInfos,
			Set<AcxAdmissionInfo> acxAdmissionInfos,
			Set<AcxUserRoles> acxUserRoleses,
			Set<AcxPollVoters> acxPollVoterses,
			Set<AcxScheduler> acxSchedulers,
			Set<AcxDocumentMaster> acxDocumentMastersForModifiedBy,
			Set<AcxDocumentMaster> acxDocumentMastersForCreatedBy,
			Set<AcxMeetingParticipents> acxMeetingParticipentses,
			Set<AcxOnlinePoll> acxOnlinePolls,
			Set<AcxStudentHealth> acxStudentHealths,
			Set<AcxExamSchedule> acxExamSchedules,
			Set<AcxStudentInfo> acxStudentInfos,
			Set<AcxTeacherInfo> acxTeacherInfos,
			Set<AcxTeacherSubjects> acxTeacherSubjectses) {
		this.userId = userId;
		this.acxSchoolMaster = acxSchoolMaster;
		this.password = password;
		this.name = name;
		this.address = address;
		this.contactNo = contactNo;
		this.emailId = emailId;
		this.birthDate = birthDate;
		this.sex = sex;
		this.acxAttendancesForTeacherId = acxAttendancesForTeacherId;
		this.acxAttendancesForStudentId = acxAttendancesForStudentId;
		this.acxUserDocumentses = acxUserDocumentses;
		this.acxParentChildsForParentId = acxParentChildsForParentId;
		this.acxExamResultsForStudentId = acxExamResultsForStudentId;
		this.acxExamSeatingArrangements = acxExamSeatingArrangements;
		this.acxTeacherNoteses = acxTeacherNoteses;
		this.acxExamResultsForExaminorId = acxExamResultsForExaminorId;
		this.acxParentChildsForChildId = acxParentChildsForChildId;
		this.acxNoticeses = acxNoticeses;
		this.acxParentInfos = acxParentInfos;
		this.acxAdmissionInfos = acxAdmissionInfos;
		this.acxUserRoleses = acxUserRoleses;
		this.acxPollVoterses = acxPollVoterses;
		this.acxSchedulers = acxSchedulers;
		this.acxDocumentMastersForModifiedBy = acxDocumentMastersForModifiedBy;
		this.acxDocumentMastersForCreatedBy = acxDocumentMastersForCreatedBy;
		this.acxMeetingParticipentses = acxMeetingParticipentses;
		this.acxOnlinePolls = acxOnlinePolls;
		this.acxStudentHealths = acxStudentHealths;
		this.acxExamSchedules = acxExamSchedules;
		this.acxStudentInfos = acxStudentInfos;
		this.acxTeacherInfos = acxTeacherInfos;
		this.acxTeacherSubjectses = acxTeacherSubjectses;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false, length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id", nullable = false)
	public AcxSchoolMaster getAcxSchoolMaster() {
		return this.acxSchoolMaster;
	}

	public void setAcxSchoolMaster(AcxSchoolMaster acxSchoolMaster) {
		this.acxSchoolMaster = acxSchoolMaster;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "contact_no", nullable = false, length = 45)
	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	@Column(name = "email_id", nullable = false, length = 100)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birth_date", length = 10)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "sex", length = 10)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsersByTeacherId")
	public Set<AcxAttendance> getAcxAttendancesForTeacherId() {
		return this.acxAttendancesForTeacherId;
	}

	public void setAcxAttendancesForTeacherId(
			Set<AcxAttendance> acxAttendancesForTeacherId) {
		this.acxAttendancesForTeacherId = acxAttendancesForTeacherId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsersByStudentId")
	public Set<AcxAttendance> getAcxAttendancesForStudentId() {
		return this.acxAttendancesForStudentId;
	}

	public void setAcxAttendancesForStudentId(
			Set<AcxAttendance> acxAttendancesForStudentId) {
		this.acxAttendancesForStudentId = acxAttendancesForStudentId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<AcxUserDocuments> getAcxUserDocumentses() {
		return this.acxUserDocumentses;
	}

	public void setAcxUserDocumentses(Set<AcxUserDocuments> acxUserDocumentses) {
		this.acxUserDocumentses = acxUserDocumentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsersByParentId")
	public Set<AcxParentChild> getAcxParentChildsForParentId() {
		return this.acxParentChildsForParentId;
	}

	public void setAcxParentChildsForParentId(
			Set<AcxParentChild> acxParentChildsForParentId) {
		this.acxParentChildsForParentId = acxParentChildsForParentId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsersByStudentId")
	public Set<AcxExamResult> getAcxExamResultsForStudentId() {
		return this.acxExamResultsForStudentId;
	}

	public void setAcxExamResultsForStudentId(
			Set<AcxExamResult> acxExamResultsForStudentId) {
		this.acxExamResultsForStudentId = acxExamResultsForStudentId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<AcxExamSeatingArrangement> getAcxExamSeatingArrangements() {
		return this.acxExamSeatingArrangements;
	}

	public void setAcxExamSeatingArrangements(
			Set<AcxExamSeatingArrangement> acxExamSeatingArrangements) {
		this.acxExamSeatingArrangements = acxExamSeatingArrangements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<AcxTeacherNotes> getAcxTeacherNoteses() {
		return this.acxTeacherNoteses;
	}

	public void setAcxTeacherNoteses(Set<AcxTeacherNotes> acxTeacherNoteses) {
		this.acxTeacherNoteses = acxTeacherNoteses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsersByExaminorId")
	public Set<AcxExamResult> getAcxExamResultsForExaminorId() {
		return this.acxExamResultsForExaminorId;
	}

	public void setAcxExamResultsForExaminorId(
			Set<AcxExamResult> acxExamResultsForExaminorId) {
		this.acxExamResultsForExaminorId = acxExamResultsForExaminorId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsersByChildId")
	public Set<AcxParentChild> getAcxParentChildsForChildId() {
		return this.acxParentChildsForChildId;
	}

	public void setAcxParentChildsForChildId(
			Set<AcxParentChild> acxParentChildsForChildId) {
		this.acxParentChildsForChildId = acxParentChildsForChildId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<AcxNotices> getAcxNoticeses() {
		return this.acxNoticeses;
	}

	public void setAcxNoticeses(Set<AcxNotices> acxNoticeses) {
		this.acxNoticeses = acxNoticeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<AcxParentInfo> getAcxParentInfos() {
		return this.acxParentInfos;
	}

	public void setAcxParentInfos(Set<AcxParentInfo> acxParentInfos) {
		this.acxParentInfos = acxParentInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<AcxAdmissionInfo> getAcxAdmissionInfos() {
		return this.acxAdmissionInfos;
	}

	public void setAcxAdmissionInfos(Set<AcxAdmissionInfo> acxAdmissionInfos) {
		this.acxAdmissionInfos = acxAdmissionInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<AcxUserRoles> getAcxUserRoleses() {
		return this.acxUserRoleses;
	}

	public void setAcxUserRoleses(Set<AcxUserRoles> acxUserRoleses) {
		this.acxUserRoleses = acxUserRoleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<AcxPollVoters> getAcxPollVoterses() {
		return this.acxPollVoterses;
	}

	public void setAcxPollVoterses(Set<AcxPollVoters> acxPollVoterses) {
		this.acxPollVoterses = acxPollVoterses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<AcxScheduler> getAcxSchedulers() {
		return this.acxSchedulers;
	}

	public void setAcxSchedulers(Set<AcxScheduler> acxSchedulers) {
		this.acxSchedulers = acxSchedulers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsersByModifiedBy")
	public Set<AcxDocumentMaster> getAcxDocumentMastersForModifiedBy() {
		return this.acxDocumentMastersForModifiedBy;
	}

	public void setAcxDocumentMastersForModifiedBy(
			Set<AcxDocumentMaster> acxDocumentMastersForModifiedBy) {
		this.acxDocumentMastersForModifiedBy = acxDocumentMastersForModifiedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsersByCreatedBy")
	public Set<AcxDocumentMaster> getAcxDocumentMastersForCreatedBy() {
		return this.acxDocumentMastersForCreatedBy;
	}

	public void setAcxDocumentMastersForCreatedBy(
			Set<AcxDocumentMaster> acxDocumentMastersForCreatedBy) {
		this.acxDocumentMastersForCreatedBy = acxDocumentMastersForCreatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<AcxMeetingParticipents> getAcxMeetingParticipentses() {
		return this.acxMeetingParticipentses;
	}

	public void setAcxMeetingParticipentses(
			Set<AcxMeetingParticipents> acxMeetingParticipentses) {
		this.acxMeetingParticipentses = acxMeetingParticipentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<AcxOnlinePoll> getAcxOnlinePolls() {
		return this.acxOnlinePolls;
	}

	public void setAcxOnlinePolls(Set<AcxOnlinePoll> acxOnlinePolls) {
		this.acxOnlinePolls = acxOnlinePolls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<AcxStudentHealth> getAcxStudentHealths() {
		return this.acxStudentHealths;
	}

	public void setAcxStudentHealths(Set<AcxStudentHealth> acxStudentHealths) {
		this.acxStudentHealths = acxStudentHealths;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<AcxExamSchedule> getAcxExamSchedules() {
		return this.acxExamSchedules;
	}

	public void setAcxExamSchedules(Set<AcxExamSchedule> acxExamSchedules) {
		this.acxExamSchedules = acxExamSchedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<AcxStudentInfo> getAcxStudentInfos() {
		return this.acxStudentInfos;
	}

	public void setAcxStudentInfos(Set<AcxStudentInfo> acxStudentInfos) {
		this.acxStudentInfos = acxStudentInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<AcxTeacherInfo> getAcxTeacherInfos() {
		return this.acxTeacherInfos;
	}

	public void setAcxTeacherInfos(Set<AcxTeacherInfo> acxTeacherInfos) {
		this.acxTeacherInfos = acxTeacherInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<AcxTeacherSubjects> getAcxTeacherSubjectses() {
		return this.acxTeacherSubjectses;
	}

	public void setAcxTeacherSubjectses(
			Set<AcxTeacherSubjects> acxTeacherSubjectses) {
		this.acxTeacherSubjectses = acxTeacherSubjectses;
	}

}
