package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

/**
 * AcxUserDocuments generated by hbm2java
 */
public class AcxUserDocuments implements java.io.Serializable {

	private int id;
	private String userId;
	private int documentId;

	public AcxUserDocuments() {
	}

	public AcxUserDocuments(int id, String userId, int documentId) {
		this.id = id;
		this.userId = userId;
		this.documentId = documentId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public int getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(int documentId) {
		this.documentId = documentId;
	}

}
