package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxUserDocuments generated by hbm2java
 */
@Entity
@Table(name = "acx_user_documents")
public class AcxUserDocuments implements java.io.Serializable {

	private int id;
	private AcxDocumentMaster acxDocumentMaster;
	private AcxUsers acxUsers;

	public AcxUserDocuments() {
	}

	public AcxUserDocuments(int id, AcxDocumentMaster acxDocumentMaster,
			AcxUsers acxUsers) {
		this.id = id;
		this.acxDocumentMaster = acxDocumentMaster;
		this.acxUsers = acxUsers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "document_id", nullable = false)
	public AcxDocumentMaster getAcxDocumentMaster() {
		return this.acxDocumentMaster;
	}

	public void setAcxDocumentMaster(AcxDocumentMaster acxDocumentMaster) {
		this.acxDocumentMaster = acxDocumentMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public AcxUsers getAcxUsers() {
		return this.acxUsers;
	}

	public void setAcxUsers(AcxUsers acxUsers) {
		this.acxUsers = acxUsers;
	}

}
