package com.xinov.academix.models;

// Generated Mar 17, 2015 12:04:16 AM by Hibernate Tools 3.4.0.CR1

/**
 * AcxUserRoles generated by hbm2java
 */
public class AcxUserRoles implements java.io.Serializable {

	private int id;
	private String userId;
	private int roleId;

	public AcxUserRoles() {
	}

	public AcxUserRoles(int id, String userId, int roleId) {
		this.id = id;
		this.userId = userId;
		this.roleId = roleId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

}
