package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxAdmissionFees generated by hbm2java
 */
@Entity
@Table(name = "acx_admission_fees")
public class AdmissionFees implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7765489691682012970L;
	
	private int id;
	private AdmissionInfo acxAdmissionInfo;
	private FeesMaster acxFeesMaster;
	private Status acxStatusMaster;

	public AdmissionFees() {
	}

	public AdmissionFees(int id, AdmissionInfo acxAdmissionInfo,
			FeesMaster acxFeesMaster, Status acxStatusMaster) {
		this.id = id;
		this.acxAdmissionInfo = acxAdmissionInfo;
		this.acxFeesMaster = acxFeesMaster;
		this.acxStatusMaster = acxStatusMaster;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "application_id", nullable = false)
	public AdmissionInfo getAcxAdmissionInfo() {
		return this.acxAdmissionInfo;
	}

	public void setAcxAdmissionInfo(AdmissionInfo acxAdmissionInfo) {
		this.acxAdmissionInfo = acxAdmissionInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fees_id", nullable = false)
	public FeesMaster getAcxFeesMaster() {
		return this.acxFeesMaster;
	}

	public void setAcxFeesMaster(FeesMaster acxFeesMaster) {
		this.acxFeesMaster = acxFeesMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fees_status_id", nullable = false)
	public Status getAcxStatusMaster() {
		return this.acxStatusMaster;
	}

	public void setAcxStatusMaster(Status acxStatusMaster) {
		this.acxStatusMaster = acxStatusMaster;
	}

}
