package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AcxClassMaster generated by hbm2java
 */
@Entity
@Table(name = "acx_class_master")
public class ClassMaster implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2752669770742057029L;
	
	private int id;
	private SchoolInfo acxSchoolMaster;
	private String title;
	private Set<Attendance> acxAttendances = new HashSet<Attendance>(0);
	private Set<Notice> acxNoticeses = new HashSet<Notice>(0);
	private Set<ExamSchedule> acxExamSchedules = new HashSet<ExamSchedule>(
			0);
	private Set<StudentInfo> acxStudentInfos = new HashSet<StudentInfo>(0);
	private Set<Scheduler> acxSchedulers = new HashSet<Scheduler>(0);

	public ClassMaster() {
	}

	public ClassMaster(int id, SchoolInfo acxSchoolMaster, String title) {
		this.id = id;
		this.acxSchoolMaster = acxSchoolMaster;
		this.title = title;
	}

	public ClassMaster(int id, SchoolInfo acxSchoolMaster,
			String title, Set<Attendance> acxAttendances,
			Set<Notice> acxNoticeses,
			Set<ExamSchedule> acxExamSchedules,
			Set<StudentInfo> acxStudentInfos, Set<Scheduler> acxSchedulers) {
		this.id = id;
		this.acxSchoolMaster = acxSchoolMaster;
		this.title = title;
		this.acxAttendances = acxAttendances;
		this.acxNoticeses = acxNoticeses;
		this.acxExamSchedules = acxExamSchedules;
		this.acxStudentInfos = acxStudentInfos;
		this.acxSchedulers = acxSchedulers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id", nullable = false)
	public SchoolInfo getAcxSchoolMaster() {
		return this.acxSchoolMaster;
	}

	public void setAcxSchoolMaster(SchoolInfo acxSchoolMaster) {
		this.acxSchoolMaster = acxSchoolMaster;
	}

	@Column(name = "title", nullable = false, length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxClassMaster")
	public Set<Attendance> getAcxAttendances() {
		return this.acxAttendances;
	}

	public void setAcxAttendances(Set<Attendance> acxAttendances) {
		this.acxAttendances = acxAttendances;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxClassMaster")
	public Set<Notice> getAcxNoticeses() {
		return this.acxNoticeses;
	}

	public void setAcxNoticeses(Set<Notice> acxNoticeses) {
		this.acxNoticeses = acxNoticeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxClassMaster")
	public Set<ExamSchedule> getAcxExamSchedules() {
		return this.acxExamSchedules;
	}

	public void setAcxExamSchedules(Set<ExamSchedule> acxExamSchedules) {
		this.acxExamSchedules = acxExamSchedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxClassMaster")
	public Set<StudentInfo> getAcxStudentInfos() {
		return this.acxStudentInfos;
	}

	public void setAcxStudentInfos(Set<StudentInfo> acxStudentInfos) {
		this.acxStudentInfos = acxStudentInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxClassMaster")
	public Set<Scheduler> getAcxSchedulers() {
		return this.acxSchedulers;
	}

	public void setAcxSchedulers(Set<Scheduler> acxSchedulers) {
		this.acxSchedulers = acxSchedulers;
	}

}
