package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AcxDocumentMaster generated by hbm2java
 */
@Entity
@Table(name = "acx_document_master")
public class DocumentMaster implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5158479167760839817L;
	
	private int id;
	private User acxUsersByModifiedBy;
	private User acxUsersByCreatedBy;
	private String documentName;
	private String documentPath;
	private Date createdDate;
	private Date modifiedDate;
	private Set<UserDocuments> acxUserDocumentses = new HashSet<UserDocuments>(
			0);
	private Set<AdmissionDocuments> acxAdmissionDocumentses = new HashSet<AdmissionDocuments>(
			0);

	public DocumentMaster() {
	}

	public DocumentMaster(int id, User acxUsersByCreatedBy,
			String documentName, String documentPath) {
		this.id = id;
		this.acxUsersByCreatedBy = acxUsersByCreatedBy;
		this.documentName = documentName;
		this.documentPath = documentPath;
	}

	public DocumentMaster(int id, User acxUsersByModifiedBy,
			User acxUsersByCreatedBy, String documentName,
			String documentPath, Date createdDate, Date modifiedDate,
			Set<UserDocuments> acxUserDocumentses,
			Set<AdmissionDocuments> acxAdmissionDocumentses) {
		this.id = id;
		this.acxUsersByModifiedBy = acxUsersByModifiedBy;
		this.acxUsersByCreatedBy = acxUsersByCreatedBy;
		this.documentName = documentName;
		this.documentPath = documentPath;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.acxUserDocumentses = acxUserDocumentses;
		this.acxAdmissionDocumentses = acxAdmissionDocumentses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modified_by")
	public User getAcxUsersByModifiedBy() {
		return this.acxUsersByModifiedBy;
	}

	public void setAcxUsersByModifiedBy(User acxUsersByModifiedBy) {
		this.acxUsersByModifiedBy = acxUsersByModifiedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public User getAcxUsersByCreatedBy() {
		return this.acxUsersByCreatedBy;
	}

	public void setAcxUsersByCreatedBy(User acxUsersByCreatedBy) {
		this.acxUsersByCreatedBy = acxUsersByCreatedBy;
	}

	@Column(name = "document_name", nullable = false)
	public String getDocumentName() {
		return this.documentName;
	}

	public void setDocumentName(String documentName) {
		this.documentName = documentName;
	}

	@Column(name = "document_path", nullable = false)
	public String getDocumentPath() {
		return this.documentPath;
	}

	public void setDocumentPath(String documentPath) {
		this.documentPath = documentPath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxDocumentMaster")
	public Set<UserDocuments> getAcxUserDocumentses() {
		return this.acxUserDocumentses;
	}

	public void setAcxUserDocumentses(Set<UserDocuments> acxUserDocumentses) {
		this.acxUserDocumentses = acxUserDocumentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxDocumentMaster")
	public Set<AdmissionDocuments> getAcxAdmissionDocumentses() {
		return this.acxAdmissionDocumentses;
	}

	public void setAcxAdmissionDocumentses(
			Set<AdmissionDocuments> acxAdmissionDocumentses) {
		this.acxAdmissionDocumentses = acxAdmissionDocumentses;
	}

}
