package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxMeetingParticipents generated by hbm2java
 */
@Entity
@Table(name = "acx_meeting_participents")
public class MeetingParticipents implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1746651768914087494L;
	
	private int id;
	private Meetings acxMeetings;
	private User acxUsers;

	public MeetingParticipents() {
	}

	public MeetingParticipents(int id, Meetings acxMeetings,
			User acxUsers) {
		this.id = id;
		this.acxMeetings = acxMeetings;
		this.acxUsers = acxUsers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "meeting_id", nullable = false)
	public Meetings getAcxMeetings() {
		return this.acxMeetings;
	}

	public void setAcxMeetings(Meetings acxMeetings) {
		this.acxMeetings = acxMeetings;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "participant_id", nullable = false)
	public User getAcxUsers() {
		return this.acxUsers;
	}

	public void setAcxUsers(User acxUsers) {
		this.acxUsers = acxUsers;
	}

}
