package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AcxMeetings generated by hbm2java
 */
@Entity
@Table(name = "acx_meetings")
public class Meetings implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8958221565594812935L;
	
	private int id;
	private MeetingType acxMeetingTypes;
	private SchoolInfo acxSchoolMaster;
	private Status acxStatusMaster;
	private Date meetingDay;
	private String moms;
	private Set<MeetingParticipents> acxMeetingParticipentses = new HashSet<MeetingParticipents>(
			0);

	public Meetings() {
	}

	public Meetings(int id, MeetingType acxMeetingTypes,
			SchoolInfo acxSchoolMaster, Status acxStatusMaster) {
		this.id = id;
		this.acxMeetingTypes = acxMeetingTypes;
		this.acxSchoolMaster = acxSchoolMaster;
		this.acxStatusMaster = acxStatusMaster;
	}

	public Meetings(int id, MeetingType acxMeetingTypes,
			SchoolInfo acxSchoolMaster, Status acxStatusMaster,
			Date meetingDay, String moms,
			Set<MeetingParticipents> acxMeetingParticipentses) {
		this.id = id;
		this.acxMeetingTypes = acxMeetingTypes;
		this.acxSchoolMaster = acxSchoolMaster;
		this.acxStatusMaster = acxStatusMaster;
		this.meetingDay = meetingDay;
		this.moms = moms;
		this.acxMeetingParticipentses = acxMeetingParticipentses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "meeting_type", nullable = false)
	public MeetingType getAcxMeetingTypes() {
		return this.acxMeetingTypes;
	}

	public void setAcxMeetingTypes(MeetingType acxMeetingTypes) {
		this.acxMeetingTypes = acxMeetingTypes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id", nullable = false)
	public SchoolInfo getAcxSchoolMaster() {
		return this.acxSchoolMaster;
	}

	public void setAcxSchoolMaster(SchoolInfo acxSchoolMaster) {
		this.acxSchoolMaster = acxSchoolMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "meeting_status", nullable = false)
	public Status getAcxStatusMaster() {
		return this.acxStatusMaster;
	}

	public void setAcxStatusMaster(Status acxStatusMaster) {
		this.acxStatusMaster = acxStatusMaster;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "meeting_day", length = 19)
	public Date getMeetingDay() {
		return this.meetingDay;
	}

	public void setMeetingDay(Date meetingDay) {
		this.meetingDay = meetingDay;
	}

	@Column(name = "moms", length = 1000)
	public String getMoms() {
		return this.moms;
	}

	public void setMoms(String moms) {
		this.moms = moms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxMeetings")
	public Set<MeetingParticipents> getAcxMeetingParticipentses() {
		return this.acxMeetingParticipentses;
	}

	public void setAcxMeetingParticipentses(
			Set<MeetingParticipents> acxMeetingParticipentses) {
		this.acxMeetingParticipentses = acxMeetingParticipentses;
	}

}
