package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AcxNoticeTypes generated by hbm2java
 */
@Entity
@Table(name = "acx_notice_types")
public class NoticeType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2035436690451528054L;
	
	private int id;
	private String title;
	private Set<Notice> acxNoticeses = new HashSet<Notice>(0);

	public NoticeType() {
	}

	public NoticeType(int id) {
		this.id = id;
	}

	public NoticeType(int id, String title, Set<Notice> acxNoticeses) {
		this.id = id;
		this.title = title;
		this.acxNoticeses = acxNoticeses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "title", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxNoticeTypes")
	public Set<Notice> getAcxNoticeses() {
		return this.acxNoticeses;
	}

	public void setAcxNoticeses(Set<Notice> acxNoticeses) {
		this.acxNoticeses = acxNoticeses;
	}

}
