package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AcxOnlinePoll generated by hbm2java
 */
@Entity
@Table(name = "acx_online_poll")
public class OnlinePoll implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5032312027439034331L;
	
	private int id;
	private SchoolInfo acxSchoolMaster;
	private User acxUsers;
	private String topic;
	private Date startDate;
	private String endDate;
	private Set<PollVoter> acxPollVoterses = new HashSet<PollVoter>(0);
	private Set<PollResults> acxPollResultses = new HashSet<PollResults>(
			0);

	public OnlinePoll() {
	}

	public OnlinePoll(int id, SchoolInfo acxSchoolMaster,
			User acxUsers, String topic, String endDate) {
		this.id = id;
		this.acxSchoolMaster = acxSchoolMaster;
		this.acxUsers = acxUsers;
		this.topic = topic;
		this.endDate = endDate;
	}

	public OnlinePoll(int id, SchoolInfo acxSchoolMaster,
			User acxUsers, String topic, Date startDate, String endDate,
			Set<PollVoter> acxPollVoterses,
			Set<PollResults> acxPollResultses) {
		this.id = id;
		this.acxSchoolMaster = acxSchoolMaster;
		this.acxUsers = acxUsers;
		this.topic = topic;
		this.startDate = startDate;
		this.endDate = endDate;
		this.acxPollVoterses = acxPollVoterses;
		this.acxPollResultses = acxPollResultses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id", nullable = false)
	public SchoolInfo getAcxSchoolMaster() {
		return this.acxSchoolMaster;
	}

	public void setAcxSchoolMaster(SchoolInfo acxSchoolMaster) {
		this.acxSchoolMaster = acxSchoolMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "issuer_id", nullable = false)
	public User getAcxUsers() {
		return this.acxUsers;
	}

	public void setAcxUsers(User acxUsers) {
		this.acxUsers = acxUsers;
	}

	@Column(name = "topic", nullable = false)
	public String getTopic() {
		return this.topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "end_date", nullable = false, length = 45)
	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxOnlinePoll")
	public Set<PollVoter> getAcxPollVoterses() {
		return this.acxPollVoterses;
	}

	public void setAcxPollVoterses(Set<PollVoter> acxPollVoterses) {
		this.acxPollVoterses = acxPollVoterses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxOnlinePoll")
	public Set<PollResults> getAcxPollResultses() {
		return this.acxPollResultses;
	}

	public void setAcxPollResultses(Set<PollResults> acxPollResultses) {
		this.acxPollResultses = acxPollResultses;
	}

}
