package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxParentInfo generated by hbm2java
 */
@Entity
@Table(name = "acx_parent_info")
public class ParentInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3756893899636796472L;
	
	private int id;
	private User acxUsers;
	private String occupation;
	private String qualification;
	private BigDecimal annualIncome;
	private String relationWirhStudent;

	public ParentInfo() {
	}

	public ParentInfo(int id, User acxUsers) {
		this.id = id;
		this.acxUsers = acxUsers;
	}

	public ParentInfo(int id, User acxUsers, String occupation,
			String qualification, BigDecimal annualIncome,
			String relationWirhStudent) {
		this.id = id;
		this.acxUsers = acxUsers;
		this.occupation = occupation;
		this.qualification = qualification;
		this.annualIncome = annualIncome;
		this.relationWirhStudent = relationWirhStudent;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id", nullable = false)
	public User getAcxUsers() {
		return this.acxUsers;
	}

	public void setAcxUsers(User acxUsers) {
		this.acxUsers = acxUsers;
	}

	@Column(name = "occupation", length = 45)
	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	@Column(name = "qualification", length = 45)
	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

	@Column(name = "annual_income", precision = 10)
	public BigDecimal getAnnualIncome() {
		return this.annualIncome;
	}

	public void setAnnualIncome(BigDecimal annualIncome) {
		this.annualIncome = annualIncome;
	}

	@Column(name = "relation_wirh_student", length = 45)
	public String getRelationWirhStudent() {
		return this.relationWirhStudent;
	}

	public void setRelationWirhStudent(String relationWirhStudent) {
		this.relationWirhStudent = relationWirhStudent;
	}

}
