package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxParentChild generated by hbm2java
 */
@Entity
@Table(name = "acx_parent_child")
public class ParentChild implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6939467214792249173L;
	
	private int id;
	private User acxUsersByParentId;
	private User acxUsersByChildId;

	public ParentChild() {
	}

	public ParentChild(int id, User acxUsersByParentId,
			User acxUsersByChildId) {
		this.id = id;
		this.acxUsersByParentId = acxUsersByParentId;
		this.acxUsersByChildId = acxUsersByChildId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id", nullable = false)
	public User getAcxUsersByParentId() {
		return this.acxUsersByParentId;
	}

	public void setAcxUsersByParentId(User acxUsersByParentId) {
		this.acxUsersByParentId = acxUsersByParentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "child_id", nullable = false)
	public User getAcxUsersByChildId() {
		return this.acxUsersByChildId;
	}

	public void setAcxUsersByChildId(User acxUsersByChildId) {
		this.acxUsersByChildId = acxUsersByChildId;
	}

}
