package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxPollResults generated by hbm2java
 */
@Entity
@Table(name = "acx_poll_results")
public class PollResults implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7041902334107592865L;
	
	private int id;
	private OnlinePoll acxOnlinePoll;
	private String answer;
	private int numberOfVotes;

	public PollResults() {
	}

	public PollResults(int id, OnlinePoll acxOnlinePoll, String answer,
			int numberOfVotes) {
		this.id = id;
		this.acxOnlinePoll = acxOnlinePoll;
		this.answer = answer;
		this.numberOfVotes = numberOfVotes;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "poll_id", nullable = false)
	public OnlinePoll getAcxOnlinePoll() {
		return this.acxOnlinePoll;
	}

	public void setAcxOnlinePoll(OnlinePoll acxOnlinePoll) {
		this.acxOnlinePoll = acxOnlinePoll;
	}

	@Column(name = "answer", nullable = false, length = 45)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	@Column(name = "number_of_votes", nullable = false)
	public int getNumberOfVotes() {
		return this.numberOfVotes;
	}

	public void setNumberOfVotes(int numberOfVotes) {
		this.numberOfVotes = numberOfVotes;
	}

}
