package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxPollVoters generated by hbm2java
 */
@Entity
@Table(name = "acx_poll_voters")
public class PollVoter implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6265418090270033086L;
	
	private int id;
	private OnlinePoll acxOnlinePoll;
	private User acxUsers;

	public PollVoter() {
	}

	public PollVoter(int id, OnlinePoll acxOnlinePoll, User acxUsers) {
		this.id = id;
		this.acxOnlinePoll = acxOnlinePoll;
		this.acxUsers = acxUsers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "poll_id", nullable = false)
	public OnlinePoll getAcxOnlinePoll() {
		return this.acxOnlinePoll;
	}

	public void setAcxOnlinePoll(OnlinePoll acxOnlinePoll) {
		this.acxOnlinePoll = acxOnlinePoll;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "voter_id", nullable = false)
	public User getAcxUsers() {
		return this.acxUsers;
	}

	public void setAcxUsers(User acxUsers) {
		this.acxUsers = acxUsers;
	}

}
