package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcxScheduler generated by hbm2java
 */
@Entity
@Table(name = "acx_scheduler")
public class Scheduler implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8502231262362948890L;
	
	private int id;
	private ClassMaster acxClassMaster;
	private Subject acxSubjectMaster;
	private User acxUsers;
	private String day;
	private Integer lectureNo;

	public Scheduler() {
	}

	public Scheduler(int id, ClassMaster acxClassMaster,
			Subject acxSubjectMaster, User acxUsers, String day) {
		this.id = id;
		this.acxClassMaster = acxClassMaster;
		this.acxSubjectMaster = acxSubjectMaster;
		this.acxUsers = acxUsers;
		this.day = day;
	}

	public Scheduler(int id, ClassMaster acxClassMaster,
			Subject acxSubjectMaster, User acxUsers, String day,
			Integer lectureNo) {
		this.id = id;
		this.acxClassMaster = acxClassMaster;
		this.acxSubjectMaster = acxSubjectMaster;
		this.acxUsers = acxUsers;
		this.day = day;
		this.lectureNo = lectureNo;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id", nullable = false)
	public ClassMaster getAcxClassMaster() {
		return this.acxClassMaster;
	}

	public void setAcxClassMaster(ClassMaster acxClassMaster) {
		this.acxClassMaster = acxClassMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_id", nullable = false)
	public Subject getAcxSubjectMaster() {
		return this.acxSubjectMaster;
	}

	public void setAcxSubjectMaster(Subject acxSubjectMaster) {
		this.acxSubjectMaster = acxSubjectMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teacher_id", nullable = false)
	public User getAcxUsers() {
		return this.acxUsers;
	}

	public void setAcxUsers(User acxUsers) {
		this.acxUsers = acxUsers;
	}

	@Column(name = "day", nullable = false, length = 45)
	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	@Column(name = "lecture_no")
	public Integer getLectureNo() {
		return this.lectureNo;
	}

	public void setLectureNo(Integer lectureNo) {
		this.lectureNo = lectureNo;
	}

}
