package com.xinov.academix.models;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AcxUsers generated by hbm2java
 */
@Entity
@Table(name = "acx_users")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7419521278061128070L;
	
	private String userId;
	private SchoolInfo acxSchoolMaster;
	private String password;
	private String name;
	private String address;
	private String contactNo;
	private String emailId;
	private Date birthDate;
	private String sex;
	
	private Set<Attendance> acxAttendancesForTeacherId = new HashSet<Attendance>(
			0);
	private Set<Attendance> acxAttendancesForStudentId = new HashSet<Attendance>(
			0);
	private Set<UserDocuments> acxUserDocumentses = new HashSet<UserDocuments>(
			0);
	private Set<ParentChild> acxParentChildsForParentId = new HashSet<ParentChild>(
			0);
	private Set<ExamResult> acxExamResultsForStudentId = new HashSet<ExamResult>(
			0);
	private Set<ExamSeatingArrangement> acxExamSeatingArrangements = new HashSet<ExamSeatingArrangement>(
			0);
	private Set<TeacherNotes> acxTeacherNoteses = new HashSet<TeacherNotes>(
			0);
	private Set<ExamResult> acxExamResultsForExaminorId = new HashSet<ExamResult>(
			0);
	private Set<ParentChild> acxParentChildsForChildId = new HashSet<ParentChild>(
			0);
	private Set<Notice> acxNoticeses = new HashSet<Notice>(0);
	private Set<ParentInfo> acxParentInfos = new HashSet<ParentInfo>(0);
	private Set<AdmissionInfo> acxAdmissionInfos = new HashSet<AdmissionInfo>(
			0);
	private Set<UserRoles> acxUserRoleses = new HashSet<UserRoles>(0);
	private Set<PollVoter> acxPollVoterses = new HashSet<PollVoter>(0);
	private Set<Scheduler> acxSchedulers = new HashSet<Scheduler>(0);
	private Set<DocumentMaster> acxDocumentMastersForModifiedBy = new HashSet<DocumentMaster>(
			0);
	private Set<DocumentMaster> acxDocumentMastersForCreatedBy = new HashSet<DocumentMaster>(
			0);
	private Set<MeetingParticipents> acxMeetingParticipentses = new HashSet<MeetingParticipents>(
			0);
	private Set<OnlinePoll> acxOnlinePolls = new HashSet<OnlinePoll>(0);
	private Set<StudentHealth> acxStudentHealths = new HashSet<StudentHealth>(
			0);
	private Set<ExamSchedule> acxExamSchedules = new HashSet<ExamSchedule>(
			0);
	private Set<StudentInfo> acxStudentInfos = new HashSet<StudentInfo>(0);
	private Set<TeacherInfo> acxTeacherInfos = new HashSet<TeacherInfo>(0);
	private Set<TeacherSubject> acxTeacherSubjectses = new HashSet<TeacherSubject>(
			0);

	public User() {
	}

	public User(String userId, SchoolInfo acxSchoolMaster,
			String password, String name, String address, String contactNo,
			String emailId) {
		this.userId = userId;
		this.acxSchoolMaster = acxSchoolMaster;
		this.password = password;
		this.name = name;
		this.address = address;
		this.contactNo = contactNo;
		this.emailId = emailId;
	}

	public User(String userId, SchoolInfo acxSchoolMaster,
			String password, String name, String address, String contactNo,
			String emailId, Date birthDate, String sex,
			Set<Attendance> acxAttendancesForTeacherId,
			Set<Attendance> acxAttendancesForStudentId,
			Set<UserDocuments> acxUserDocumentses,
			Set<ParentChild> acxParentChildsForParentId,
			Set<ExamResult> acxExamResultsForStudentId,
			Set<ExamSeatingArrangement> acxExamSeatingArrangements,
			Set<TeacherNotes> acxTeacherNoteses,
			Set<ExamResult> acxExamResultsForExaminorId,
			Set<ParentChild> acxParentChildsForChildId,
			Set<Notice> acxNoticeses, Set<ParentInfo> acxParentInfos,
			Set<AdmissionInfo> acxAdmissionInfos,
			Set<UserRoles> acxUserRoleses,
			Set<PollVoter> acxPollVoterses,
			Set<Scheduler> acxSchedulers,
			Set<DocumentMaster> acxDocumentMastersForModifiedBy,
			Set<DocumentMaster> acxDocumentMastersForCreatedBy,
			Set<MeetingParticipents> acxMeetingParticipentses,
			Set<OnlinePoll> acxOnlinePolls,
			Set<StudentHealth> acxStudentHealths,
			Set<ExamSchedule> acxExamSchedules,
			Set<StudentInfo> acxStudentInfos,
			Set<TeacherInfo> acxTeacherInfos,
			Set<TeacherSubject> acxTeacherSubjectses) {
		this.userId = userId;
		this.acxSchoolMaster = acxSchoolMaster;
		this.password = password;
		this.name = name;
		this.address = address;
		this.contactNo = contactNo;
		this.emailId = emailId;
		this.birthDate = birthDate;
		this.sex = sex;
		this.acxAttendancesForTeacherId = acxAttendancesForTeacherId;
		this.acxAttendancesForStudentId = acxAttendancesForStudentId;
		this.acxUserDocumentses = acxUserDocumentses;
		this.acxParentChildsForParentId = acxParentChildsForParentId;
		this.acxExamResultsForStudentId = acxExamResultsForStudentId;
		this.acxExamSeatingArrangements = acxExamSeatingArrangements;
		this.acxTeacherNoteses = acxTeacherNoteses;
		this.acxExamResultsForExaminorId = acxExamResultsForExaminorId;
		this.acxParentChildsForChildId = acxParentChildsForChildId;
		this.acxNoticeses = acxNoticeses;
		this.acxParentInfos = acxParentInfos;
		this.acxAdmissionInfos = acxAdmissionInfos;
		this.acxUserRoleses = acxUserRoleses;
		this.acxPollVoterses = acxPollVoterses;
		this.acxSchedulers = acxSchedulers;
		this.acxDocumentMastersForModifiedBy = acxDocumentMastersForModifiedBy;
		this.acxDocumentMastersForCreatedBy = acxDocumentMastersForCreatedBy;
		this.acxMeetingParticipentses = acxMeetingParticipentses;
		this.acxOnlinePolls = acxOnlinePolls;
		this.acxStudentHealths = acxStudentHealths;
		this.acxExamSchedules = acxExamSchedules;
		this.acxStudentInfos = acxStudentInfos;
		this.acxTeacherInfos = acxTeacherInfos;
		this.acxTeacherSubjectses = acxTeacherSubjectses;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false, length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id", nullable = false)
	public SchoolInfo getAcxSchoolMaster() {
		return this.acxSchoolMaster;
	}

	public void setAcxSchoolMaster(SchoolInfo acxSchoolMaster) {
		this.acxSchoolMaster = acxSchoolMaster;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "contact_no", nullable = false, length = 45)
	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	@Column(name = "email_id", nullable = false, length = 100)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birth_date", length = 10)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "sex", length = 10)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsersByTeacherId")
	public Set<Attendance> getAcxAttendancesForTeacherId() {
		return this.acxAttendancesForTeacherId;
	}

	public void setAcxAttendancesForTeacherId(
			Set<Attendance> acxAttendancesForTeacherId) {
		this.acxAttendancesForTeacherId = acxAttendancesForTeacherId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsersByStudentId")
	public Set<Attendance> getAcxAttendancesForStudentId() {
		return this.acxAttendancesForStudentId;
	}

	public void setAcxAttendancesForStudentId(
			Set<Attendance> acxAttendancesForStudentId) {
		this.acxAttendancesForStudentId = acxAttendancesForStudentId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<UserDocuments> getAcxUserDocumentses() {
		return this.acxUserDocumentses;
	}

	public void setAcxUserDocumentses(Set<UserDocuments> acxUserDocumentses) {
		this.acxUserDocumentses = acxUserDocumentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsersByParentId")
	public Set<ParentChild> getAcxParentChildsForParentId() {
		return this.acxParentChildsForParentId;
	}

	public void setAcxParentChildsForParentId(
			Set<ParentChild> acxParentChildsForParentId) {
		this.acxParentChildsForParentId = acxParentChildsForParentId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsersByStudentId")
	public Set<ExamResult> getAcxExamResultsForStudentId() {
		return this.acxExamResultsForStudentId;
	}

	public void setAcxExamResultsForStudentId(
			Set<ExamResult> acxExamResultsForStudentId) {
		this.acxExamResultsForStudentId = acxExamResultsForStudentId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<ExamSeatingArrangement> getAcxExamSeatingArrangements() {
		return this.acxExamSeatingArrangements;
	}

	public void setAcxExamSeatingArrangements(
			Set<ExamSeatingArrangement> acxExamSeatingArrangements) {
		this.acxExamSeatingArrangements = acxExamSeatingArrangements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<TeacherNotes> getAcxTeacherNoteses() {
		return this.acxTeacherNoteses;
	}

	public void setAcxTeacherNoteses(Set<TeacherNotes> acxTeacherNoteses) {
		this.acxTeacherNoteses = acxTeacherNoteses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsersByExaminorId")
	public Set<ExamResult> getAcxExamResultsForExaminorId() {
		return this.acxExamResultsForExaminorId;
	}

	public void setAcxExamResultsForExaminorId(
			Set<ExamResult> acxExamResultsForExaminorId) {
		this.acxExamResultsForExaminorId = acxExamResultsForExaminorId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsersByChildId")
	public Set<ParentChild> getAcxParentChildsForChildId() {
		return this.acxParentChildsForChildId;
	}

	public void setAcxParentChildsForChildId(
			Set<ParentChild> acxParentChildsForChildId) {
		this.acxParentChildsForChildId = acxParentChildsForChildId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<Notice> getAcxNoticeses() {
		return this.acxNoticeses;
	}

	public void setAcxNoticeses(Set<Notice> acxNoticeses) {
		this.acxNoticeses = acxNoticeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<ParentInfo> getAcxParentInfos() {
		return this.acxParentInfos;
	}

	public void setAcxParentInfos(Set<ParentInfo> acxParentInfos) {
		this.acxParentInfos = acxParentInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<AdmissionInfo> getAcxAdmissionInfos() {
		return this.acxAdmissionInfos;
	}

	public void setAcxAdmissionInfos(Set<AdmissionInfo> acxAdmissionInfos) {
		this.acxAdmissionInfos = acxAdmissionInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<UserRoles> getAcxUserRoleses() {
		return this.acxUserRoleses;
	}

	public void setAcxUserRoleses(Set<UserRoles> acxUserRoleses) {
		this.acxUserRoleses = acxUserRoleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<PollVoter> getAcxPollVoterses() {
		return this.acxPollVoterses;
	}

	public void setAcxPollVoterses(Set<PollVoter> acxPollVoterses) {
		this.acxPollVoterses = acxPollVoterses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<Scheduler> getAcxSchedulers() {
		return this.acxSchedulers;
	}

	public void setAcxSchedulers(Set<Scheduler> acxSchedulers) {
		this.acxSchedulers = acxSchedulers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsersByModifiedBy")
	public Set<DocumentMaster> getAcxDocumentMastersForModifiedBy() {
		return this.acxDocumentMastersForModifiedBy;
	}

	public void setAcxDocumentMastersForModifiedBy(
			Set<DocumentMaster> acxDocumentMastersForModifiedBy) {
		this.acxDocumentMastersForModifiedBy = acxDocumentMastersForModifiedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsersByCreatedBy")
	public Set<DocumentMaster> getAcxDocumentMastersForCreatedBy() {
		return this.acxDocumentMastersForCreatedBy;
	}

	public void setAcxDocumentMastersForCreatedBy(
			Set<DocumentMaster> acxDocumentMastersForCreatedBy) {
		this.acxDocumentMastersForCreatedBy = acxDocumentMastersForCreatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<MeetingParticipents> getAcxMeetingParticipentses() {
		return this.acxMeetingParticipentses;
	}

	public void setAcxMeetingParticipentses(
			Set<MeetingParticipents> acxMeetingParticipentses) {
		this.acxMeetingParticipentses = acxMeetingParticipentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<OnlinePoll> getAcxOnlinePolls() {
		return this.acxOnlinePolls;
	}

	public void setAcxOnlinePolls(Set<OnlinePoll> acxOnlinePolls) {
		this.acxOnlinePolls = acxOnlinePolls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<StudentHealth> getAcxStudentHealths() {
		return this.acxStudentHealths;
	}

	public void setAcxStudentHealths(Set<StudentHealth> acxStudentHealths) {
		this.acxStudentHealths = acxStudentHealths;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<ExamSchedule> getAcxExamSchedules() {
		return this.acxExamSchedules;
	}

	public void setAcxExamSchedules(Set<ExamSchedule> acxExamSchedules) {
		this.acxExamSchedules = acxExamSchedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<StudentInfo> getAcxStudentInfos() {
		return this.acxStudentInfos;
	}

	public void setAcxStudentInfos(Set<StudentInfo> acxStudentInfos) {
		this.acxStudentInfos = acxStudentInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<TeacherInfo> getAcxTeacherInfos() {
		return this.acxTeacherInfos;
	}

	public void setAcxTeacherInfos(Set<TeacherInfo> acxTeacherInfos) {
		this.acxTeacherInfos = acxTeacherInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acxUsers")
	public Set<TeacherSubject> getAcxTeacherSubjectses() {
		return this.acxTeacherSubjectses;
	}

	public void setAcxTeacherSubjectses(
			Set<TeacherSubject> acxTeacherSubjectses) {
		this.acxTeacherSubjectses = acxTeacherSubjectses;
	}

}
