package com.xinov.academix.core.api.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AdmissionFees generated by hbm2java
 */
@Entity
@Table(name = "acx_admission_fees")
public class AdmissionFees implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7765489691682012970L;
	
	private int id;
	private AdmissionInfo admissionInfo;
	private FeesMaster feesMaster;
	private Status status;

	public AdmissionFees() {
	}

	public AdmissionFees(int id, AdmissionInfo admissionInfo,
			FeesMaster feesMaster, Status statusMaster) {
		this.id = id;
		this.admissionInfo = admissionInfo;
		this.feesMaster = feesMaster;
		this.status = statusMaster;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "application_id", nullable = false)
	public AdmissionInfo getAdmissionInfo() {
		return this.admissionInfo;
	}

	public void setAdmissionInfo(AdmissionInfo admissionInfo) {
		this.admissionInfo = admissionInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fees_id", nullable = false)
	public FeesMaster getFeesMaster() {
		return this.feesMaster;
	}

	public void setFeesMaster(FeesMaster feesMaster) {
		this.feesMaster = feesMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fees_status_id", nullable = false)
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

}
