package com.xinov.academix.core.api.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClassMaster generated by hbm2java
 */
@Entity
@Table(name = "acx_class_master")
public class ClassMaster implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2752669770742057029L;
	
	private int id;
	private SchoolInfo schoolInfo;
	private String title;
	private Set<Attendance> attendances = new HashSet<Attendance>(0);
	private Set<Notice> noticeses = new HashSet<Notice>(0);
	private Set<ExamSchedule> examSchedules = new HashSet<ExamSchedule>(
			0);
	private Set<StudentInfo> studentInfos = new HashSet<StudentInfo>(0);
	private Set<Scheduler> schedulers = new HashSet<Scheduler>(0);

	public ClassMaster() {
	}

	public ClassMaster(int id, SchoolInfo schoolInfo, String title) {
		this.id = id;
		this.schoolInfo = schoolInfo;
		this.title = title;
	}

	public ClassMaster(int id, SchoolInfo schoolInfo,
			String title, Set<Attendance> attendances,
			Set<Notice> noticeses,
			Set<ExamSchedule> examSchedules,
			Set<StudentInfo> studentInfos, Set<Scheduler> schedulers) {
		this.id = id;
		this.schoolInfo = schoolInfo;
		this.title = title;
		this.attendances = attendances;
		this.noticeses = noticeses;
		this.examSchedules = examSchedules;
		this.studentInfos = studentInfos;
		this.schedulers = schedulers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id", nullable = false)
	public SchoolInfo getSchoolInfo() {
		return this.schoolInfo;
	}

	public void setSchoolInfo(SchoolInfo schoolInfo) {
		this.schoolInfo = schoolInfo;
	}

	@Column(name = "title", nullable = false, length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ClassMaster")
	public Set<Attendance> getAttendances() {
		return this.attendances;
	}

	public void setAttendances(Set<Attendance> attendances) {
		this.attendances = attendances;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ClassMaster")
	public Set<Notice> getNoticeses() {
		return this.noticeses;
	}

	public void setNoticeses(Set<Notice> noticeses) {
		this.noticeses = noticeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ClassMaster")
	public Set<ExamSchedule> getExamSchedules() {
		return this.examSchedules;
	}

	public void setExamSchedules(Set<ExamSchedule> examSchedules) {
		this.examSchedules = examSchedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ClassMaster")
	public Set<StudentInfo> getStudentInfos() {
		return this.studentInfos;
	}

	public void setStudentInfos(Set<StudentInfo> studentInfos) {
		this.studentInfos = studentInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ClassMaster")
	public Set<Scheduler> getSchedulers() {
		return this.schedulers;
	}

	public void setSchedulers(Set<Scheduler> schedulers) {
		this.schedulers = schedulers;
	}

}
