package com.xinov.academix.core.api.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Exams generated by hbm2java
 */
@Entity
@Table(name = "acx_exam")
public class Examination implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7444828824900545034L;
	
	private int id;
	private SchoolInfo schoolInfo;
	private String examName;
	private Date examStartDate;
	private Date examEndDate;
	private Set<ExamResult> examResults = new HashSet<ExamResult>(0);
	private Set<ExamSeatingArrangement> examSeatingArrangements = new HashSet<ExamSeatingArrangement>(
			0);
	private Set<ExamSchedule> examSchedules = new HashSet<ExamSchedule>(
			0);

	public Examination() {
	}

	public Examination(int id, SchoolInfo schoolInfo, String examName) {
		this.id = id;
		this.schoolInfo = schoolInfo;
		this.examName = examName;
	}

	public Examination(int id, SchoolInfo schoolInfo, String examName,
			Date examStartDate, Date examEndDate,
			Set<ExamResult> examResults,
			Set<ExamSeatingArrangement> examSeatingArrangements,
			Set<ExamSchedule> examSchedules) {
		this.id = id;
		this.schoolInfo = schoolInfo;
		this.examName = examName;
		this.examStartDate = examStartDate;
		this.examEndDate = examEndDate;
		this.examResults = examResults;
		this.examSeatingArrangements = examSeatingArrangements;
		this.examSchedules = examSchedules;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id", nullable = false)
	public SchoolInfo getSchoolInfo() {
		return this.schoolInfo;
	}

	public void setSchoolInfo(SchoolInfo schoolInfo) {
		this.schoolInfo = schoolInfo;
	}

	@Column(name = "exam_name", nullable = false, length = 45)
	public String getExamName() {
		return this.examName;
	}

	public void setExamName(String examName) {
		this.examName = examName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "exam_start_date", length = 19)
	public Date getExamStartDate() {
		return this.examStartDate;
	}

	public void setExamStartDate(Date examStartDate) {
		this.examStartDate = examStartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "exam_end_date", length = 19)
	public Date getExamEndDate() {
		return this.examEndDate;
	}

	public void setExamEndDate(Date examEndDate) {
		this.examEndDate = examEndDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "Exams")
	public Set<ExamResult> getExamResults() {
		return this.examResults;
	}

	public void setExamResults(Set<ExamResult> examResults) {
		this.examResults = examResults;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "Exams")
	public Set<ExamSeatingArrangement> getExamSeatingArrangements() {
		return this.examSeatingArrangements;
	}

	public void setExamSeatingArrangements(
			Set<ExamSeatingArrangement> examSeatingArrangements) {
		this.examSeatingArrangements = examSeatingArrangements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "Exams")
	public Set<ExamSchedule> getExamSchedules() {
		return this.examSchedules;
	}

	public void setExamSchedules(Set<ExamSchedule> examSchedules) {
		this.examSchedules = examSchedules;
	}

}
