package com.xinov.academix.core.api.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExamResult generated by hbm2java
 */
@Entity
@Table(name = "acx_exam_result")
public class ExamResult implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8164093511560425335L;
	
	private int id;
	private Examination examination;
	private Subject subject;
	private User usersByStudentId;
	private User usersByExaminorId;
	private Integer totalMarks;
	private Integer marksObtained;
	private String gradeObtained;
	private BigDecimal percentage;
	private String result;
	private String remarks;

	public ExamResult() {
	}

	public ExamResult(int id, Examination examination,
			Subject subject, User usersByStudentId,
			User usersByExaminorId) {
		this.id = id;
		this.examination = examination;
		this.subject = subject;
		this.usersByStudentId = usersByStudentId;
		this.usersByExaminorId = usersByExaminorId;
	}

	public ExamResult(int id, Examination examination,
			Subject subject, User usersByStudentId,
			User usersByExaminorId, Integer totalMarks,
			Integer marksObtained, String gradeObtained, BigDecimal percentage,
			String result, String remarks) {
		this.id = id;
		this.examination = examination;
		this.subject = subject;
		this.usersByStudentId = usersByStudentId;
		this.usersByExaminorId = usersByExaminorId;
		this.totalMarks = totalMarks;
		this.marksObtained = marksObtained;
		this.gradeObtained = gradeObtained;
		this.percentage = percentage;
		this.result = result;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "exam_id", nullable = false)
	public Examination getExamination() {
		return this.examination;
	}

	public void setExamination(Examination examination) {
		this.examination = examination;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_id", nullable = false)
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id", nullable = false)
	public User getUsersByStudentId() {
		return this.usersByStudentId;
	}

	public void setUsersByStudentId(User usersByStudentId) {
		this.usersByStudentId = usersByStudentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "examinor_id", nullable = false)
	public User getUsersByExaminorId() {
		return this.usersByExaminorId;
	}

	public void setUsersByExaminorId(User usersByExaminorId) {
		this.usersByExaminorId = usersByExaminorId;
	}

	@Column(name = "total_marks")
	public Integer getTotalMarks() {
		return this.totalMarks;
	}

	public void setTotalMarks(Integer totalMarks) {
		this.totalMarks = totalMarks;
	}

	@Column(name = "marks_obtained")
	public Integer getMarksObtained() {
		return this.marksObtained;
	}

	public void setMarksObtained(Integer marksObtained) {
		this.marksObtained = marksObtained;
	}

	@Column(name = "grade_obtained", length = 45)
	public String getGradeObtained() {
		return this.gradeObtained;
	}

	public void setGradeObtained(String gradeObtained) {
		this.gradeObtained = gradeObtained;
	}

	@Column(name = "percentage", precision = 2)
	public BigDecimal getPercentage() {
		return this.percentage;
	}

	public void setPercentage(BigDecimal percentage) {
		this.percentage = percentage;
	}

	@Column(name = "result", length = 45)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Column(name = "remarks", length = 100)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
