package com.xinov.academix.core.api.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExamSchedule generated by hbm2java
 */
@Entity
@Table(name = "acx_exam_schedule")
public class ExamSchedule implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1742117427680438701L;
	
	private int id;
	private ClassMaster classMaster;
	private Examination examination;
	private Subject subject;
	private User user;
	private Date date;
	private Date startTime;
	private Date endTime;

	public ExamSchedule() {
	}

	public ExamSchedule(int id, ClassMaster classMaster,
			Examination examination, Subject subject,
			User user, Date date) {
		this.id = id;
		this.classMaster = classMaster;
		this.examination = examination;
		this.subject = subject;
		this.user = user;
		this.date = date;
	}

	public ExamSchedule(int id, ClassMaster classMaster,
			Examination examination, Subject subject,
			User user, Date date, Date startTime, Date endTime) {
		this.id = id;
		this.classMaster = classMaster;
		this.examination = examination;
		this.subject = subject;
		this.user = user;
		this.date = date;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id", nullable = false)
	public ClassMaster getClassMaster() {
		return this.classMaster;
	}

	public void setClassMaster(ClassMaster classMaster) {
		this.classMaster = classMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "exam_id", nullable = false)
	public Examination getExamination() {
		return this.examination;
	}

	public void setExamination(Examination examination) {
		this.examination = examination;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_id", nullable = false)
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "examinor_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_time", length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

}
