package com.xinov.academix.core.api.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FeesMaster generated by hbm2java
 */
@Entity
@Table(name = "acx_fees_master")
public class FeesMaster implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1849617580208848200L;
	
	private int id;
	private String title;
	private int fees;
	private Set<AdmissionFees> admissionFees = new HashSet<AdmissionFees>(
			0);

	public FeesMaster() {
	}

	public FeesMaster(int id, String title, int fees) {
		this.id = id;
		this.title = title;
		this.fees = fees;
	}

	public FeesMaster(int id, String title, int fees,
			Set<AdmissionFees> admissionFees) {
		this.id = id;
		this.title = title;
		this.fees = fees;
		this.admissionFees = admissionFees;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "fees", nullable = false)
	public int getFees() {
		return this.fees;
	}

	public void setFees(int fees) {
		this.fees = fees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "FeesMaster")
	public Set<AdmissionFees> getAdmissionFees() {
		return this.admissionFees;
	}

	public void setAdmissionFees(Set<AdmissionFees> admissionFees) {
		this.admissionFees = admissionFees;
	}

}
