package com.xinov.academix.core.api.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Meetings generated by hbm2java
 */
@Entity
@Table(name = "acx_meetings")
public class Meeting implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8958221565594812935L;
	
	private int id;
	private MeetingType meetingType;
	private SchoolInfo schoolInfo;
	private Status status;
	private Date meetingDay;
	private String moms;
	private Set<MeetingParticipent> meetingParticipents = new HashSet<MeetingParticipent>(
			0);

	public Meeting() {
	}

	public Meeting(int id, MeetingType meetingType,
			SchoolInfo schoolInfo, Status status) {
		this.id = id;
		this.meetingType = meetingType;
		this.schoolInfo = schoolInfo;
		this.status = status;
	}

	public Meeting(int id, MeetingType meetingType,
			SchoolInfo schoolInfo, Status status,
			Date meetingDay, String moms,
			Set<MeetingParticipent> meetingParticipents) {
		this.id = id;
		this.meetingType = meetingType;
		this.schoolInfo = schoolInfo;
		this.status = status;
		this.meetingDay = meetingDay;
		this.moms = moms;
		this.meetingParticipents = meetingParticipents;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "meeting_type", nullable = false)
	public MeetingType getMeetingType() {
		return this.meetingType;
	}

	public void setMeetingType(MeetingType meetingType) {
		this.meetingType = meetingType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id", nullable = false)
	public SchoolInfo getSchoolInfo() {
		return this.schoolInfo;
	}

	public void setSchoolInfo(SchoolInfo schoolInfo) {
		this.schoolInfo = schoolInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "meeting_status", nullable = false)
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "meeting_day", length = 19)
	public Date getMeetingDay() {
		return this.meetingDay;
	}

	public void setMeetingDay(Date meetingDay) {
		this.meetingDay = meetingDay;
	}

	@Column(name = "moms", length = 1000)
	public String getMoms() {
		return this.moms;
	}

	public void setMoms(String moms) {
		this.moms = moms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "Meetings")
	public Set<MeetingParticipent> getMeetingParticipents() {
		return this.meetingParticipents;
	}

	public void setMeetingParticipents(
			Set<MeetingParticipent> meetingParticipents) {
		this.meetingParticipents = meetingParticipents;
	}

}
