package com.xinov.academix.core.api.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notices generated by hbm2java
 */
@Entity
@Table(name = "acx_notices")
public class Notice implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2220738904469643567L;
	
	private int id;
	private ClassMaster classMaster;
	private NoticeType noticeType;
	private SchoolInfo schoolInfo;
	private User user;
	private String notice;
	private Date startDate;
	private Date endDate;

	public Notice() {
	}

	public Notice(int id, NoticeType noticeType,
			SchoolInfo schoolInfo, User user, String notice) {
		this.id = id;
		this.noticeType = noticeType;
		this.schoolInfo = schoolInfo;
		this.user = user;
		this.notice = notice;
	}

	public Notice(int id, ClassMaster classMaster,
			NoticeType noticeType, SchoolInfo schoolInfo,
			User user, String notice, Date startDate, Date endDate) {
		this.id = id;
		this.classMaster = classMaster;
		this.noticeType = noticeType;
		this.schoolInfo = schoolInfo;
		this.user = user;
		this.notice = notice;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id")
	public ClassMaster getClassMaster() {
		return this.classMaster;
	}

	public void setClassMaster(ClassMaster classMaster) {
		this.classMaster = classMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "notice_type", nullable = false)
	public NoticeType getNoticeType() {
		return this.noticeType;
	}

	public void setNoticeType(NoticeType noticeType) {
		this.noticeType = noticeType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id", nullable = false)
	public SchoolInfo getSchoolInfo() {
		return this.schoolInfo;
	}

	public void setSchoolInfo(SchoolInfo schoolInfo) {
		this.schoolInfo = schoolInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "issuer_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "notice", nullable = false, length = 1000)
	public String getNotice() {
		return this.notice;
	}

	public void setNotice(String notice) {
		this.notice = notice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
