package com.xinov.academix.core.api.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Scheduler generated by hbm2java
 */
@Entity
@Table(name = "acx_scheduler")
public class Scheduler implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8502231262362948890L;
	
	private int id;
	private ClassMaster classMaster;
	private Subject subject;
	private User user;
	private String day;
	private Integer lectureNo;

	public Scheduler() {
	}

	public Scheduler(int id, ClassMaster classMaster,
			Subject subject, User user, String day) {
		this.id = id;
		this.classMaster = classMaster;
		this.subject = subject;
		this.user = user;
		this.day = day;
	}

	public Scheduler(int id, ClassMaster classMaster,
			Subject subject, User user, String day,
			Integer lectureNo) {
		this.id = id;
		this.classMaster = classMaster;
		this.subject = subject;
		this.user = user;
		this.day = day;
		this.lectureNo = lectureNo;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id", nullable = false)
	public ClassMaster getClassMaster() {
		return this.classMaster;
	}

	public void setClassMaster(ClassMaster classMaster) {
		this.classMaster = classMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_id", nullable = false)
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teacher_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "day", nullable = false, length = 45)
	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	@Column(name = "lecture_no")
	public Integer getLectureNo() {
		return this.lectureNo;
	}

	public void setLectureNo(Integer lectureNo) {
		this.lectureNo = lectureNo;
	}

}
