package com.xinov.academix.core.api.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * StatusMaster generated by hbm2java
 */
@Entity
@Table(name = "acx_status_master", uniqueConstraints = @UniqueConstraint(columnNames = "title"))
public class Status implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2264546371396156117L;
	
	private int id;
	private String title;
	private String type;
	private Set<AdmissionFees> admissionFees = new HashSet<AdmissionFees>(
			0);
	private Set<Meeting> meetings = new HashSet<Meeting>(0);
	private Set<AdmissionInfo> admissionInfos = new HashSet<AdmissionInfo>(
			0);

	public Status() {
	}

	public Status(int id, String title, String type) {
		this.id = id;
		this.title = title;
		this.type = type;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "title", unique = true, nullable = false, length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "StatusMaster")
	public Set<AdmissionFees> getAdmissionFees() {
		return this.admissionFees;
	}

	public void setAdmissionFees(Set<AdmissionFees> admissionFees) {
		this.admissionFees = admissionFees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "StatusMaster")
	public Set<Meeting> getMeetings() {
		return this.meetings;
	}

	public void setMeetings(Set<Meeting> meetings) {
		this.meetings = meetings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "StatusMaster")
	public Set<AdmissionInfo> getAdmissionInfos() {
		return this.admissionInfos;
	}

	public void setAdmissionInfos(Set<AdmissionInfo> admissionInfos) {
		this.admissionInfos = admissionInfos;
	}

}
