package com.xinov.academix.core.api.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StudentInfo generated by hbm2java
 */
@Entity
@Table(name = "acx_student_info")
public class StudentInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5618044066324441543L;
	
	private int id;
	private ClassMaster classMaster;
	private User user;
	private String roleNumber;

	public StudentInfo() {
	}

	public StudentInfo(int id, ClassMaster classMaster,
			User user, String roleNumber) {
		this.id = id;
		this.classMaster = classMaster;
		this.user = user;
		this.roleNumber = roleNumber;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id", nullable = false)
	public ClassMaster getClassMaster() {
		return this.classMaster;
	}

	public void setClassMaster(ClassMaster classMaster) {
		this.classMaster = classMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "role_number", nullable = false, length = 45)
	public String getRoleNumber() {
		return this.roleNumber;
	}

	public void setRoleNumber(String roleNumber) {
		this.roleNumber = roleNumber;
	}

}
