package com.xinov.academix.core.api.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TeacherSubjects generated by hbm2java
 */
@Entity
@Table(name = "acx_teacher_subjects")
public class TeacherSubject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9040758994704881371L;
	
	private int id;
	private Subject subject;
	private User user;

	public TeacherSubject() {
	}

	public TeacherSubject(int id, Subject subject,
			User user) {
		this.id = id;
		this.subject = subject;
		this.user = user;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_id", nullable = false)
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teacher_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUsers(User user) {
		this.user = user;
	}

}
