package com.xinov.academix.core.api.model;

// Generated Mar 18, 2015 5:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserDocuments generated by hbm2java
 */
@Entity
@Table(name = "acx_user_documents")
public class UserDocument implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5930239900746277607L;
	
	private int id;
	private DocumentMaster documentMaster;
	private User user;

	public UserDocument() {
	}

	public UserDocument(int id, DocumentMaster documentMaster,
			User user) {
		this.id = id;
		this.documentMaster = documentMaster;
		this.user = user;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "document_id", nullable = false)
	public DocumentMaster getDocumentMaster() {
		return this.documentMaster;
	}

	public void setDocumentMaster(DocumentMaster documentMaster) {
		this.documentMaster = documentMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
